### DISCUSSION TITLE
How to keep same file ownership on host and in the container?

### DISCUSSION THREAD

**Discussion by alekseiismirnov** [containers/podman-compose#824] [Q&A]
Here is a part of my `podman-compose.yml`

```
  web:
    build: .
    args:
      USERNAME: ${USERNAME}
      GROUPNAME: ${GROUPNAME}
      USERID: ${USERID}
      GROUPID: ${GROUPID}
    depends_on:
      - db
    userns: keep-id

    ports:
     - "3000:3000"
    volumes:
     - .:/app:z
 ```
This is the call to the podman composer:
```
podman-compose up --build-arg USERNAME=$(id -un) --build-arg GROUPNAME=$(id -gn) --build-arg USERID=$(id -u) --build-arg GROUPID=$(id -g)
```
The `web` volume is intended to be write-accessible from both the container and the host.

However, in this configuration, the `/app` folder and its files are owned by root. If I add the 'U' flag (`- .:/app:z,U`), the folder becomes write-accessible to the container but is locally owned by a user with UID 100999 and GID 100999.

When running a container from the resulting image:

```podman run -it -v .:/home/lesha:z --userns=keep-id  --entrypoint /bin/sh quotes_web:latest ```

Ownership is correct inside the container and does not change on the host, working as expected. Any suggestions on how to fix this for `podman-compose`?

This is the Dockerfile:
```
FROM docker.io/library/ruby:3.0.0-alpine

ARG USERNAME
ARG GROUPNAME
ARG USERID
ARG GROUPID

COPY run_rails.sh /usr/local/bin
RUN chmod +x /usr/local/bin/run_rails.sh

WORKDIR /app

ENV APPPATH='/app'

RUN echo '***' && \
    addgroup -g $GROUPID $GROUPNAME && \
    adduser -S -u $USERID -G $GROUPNAME  -h /home/$USERNAME -s /bin/sh $USERNAME && \
    mkdir -p /home/$USERNAME && \
    chmod 700 /home/$USERNAME && \
    mkdir -p $APPPATH && \
    echo "export PATH=$PATH:/home/$USERNAME/.local/share/gem/ruby/3.0.0/bin" >> /home/$USERNAME/.profile && \
    echo 'gem: --user-install --env-shebang --no-rdoc --no-ri' >> /home/$USERNAME/.gemrc && \
    echo "Change ownership chown -R $USERNAME:$GROUPNAME $APPPATH" && \
    chown -R $USERNAME:$GROUPNAME $APPPATH && \
    chown -R $USERNAME:$GROUPNAME /home/$USERNAME

USER $USERNAME
ENTRYPOINT ["run_rails.sh"]

EXPOSE 3000
```

Thank you!
