### DISCUSSION TITLE
x-podman: uidmaps: has no effect

### DISCUSSION THREAD

**Discussion by jb-alvarado** [containers/podman-compose#892] [Q&A]
Hello,
I would like to run a container with mapped user and group, so I set up my yaml file to:

```YAML
networks:
  vswitch:
    external:
      name: vswitch

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    hostname: nginx
    x-podman:
      uidmaps:
        - 0:33:1
      gidmaps:
        - 0:33:1
    networks:
      vswitch:
        ipv4_address: 10.50.0.2
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/www/certbot/:/var/www/certbot/:ro
      - ./nginx/www/html/:/var/www/html/:ro
      - ./nginx/logs/:/var/log/nginx/
```

But the mapping get ignore, only when I run `podman-compose --podman-run-args="--uidmap=0:33:256 --gidmap=0:33:256" up -d` it works like it should.

My version is:

```
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.6
podman --version 
podman version 4.3.1
```

Running on debian 12

Do you have any idea why this is happen?
