### ISSUE TITLE
Cannot use long syntax port definition

### ISSUE THREAD

**Issue by ggof** [containers/podman-compose#100]
Hello!

I recently tried using this script with a docker-compose file with the long port definition syntax and it seems like it's not working. It spits out this error : `TypeError: unhashable type: 'dict'`, since it's not a string but a dict. If you need, I can provide logs with a bit more details on the issue.

For reference, the feature that is missing from the docker-compose file-parsing is [this one](https://docs.docker.com/compose/compose-file/#long-syntax-1).  It's a feature that's been added in docker-compose file v3.2.

If you need anything else, feel free to @ me.
Thank you!

**Comment by yodatak** [comment]
Same issue for me

**Comment by mokibit** [comment]
Closing this issue as it has already been resolved. Long syntax port definitions are fully supported in the current version of `podman-compose`.

Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```

Here is a minimal `compose.yml` using the long syntax:

```
services:
  web:
    image: busybox
    command: ["sleep", "infinity"]
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
```
Start the service
```
$ podman-compose -f compose.yml up -d
[...]
test-podman-compose_web_1
```
Verify the port is mapped
```
$ podman-compose -f compose.yml port web 80
8080
```
The container starts successfully and the port mapping is applied correctly, confirming that the long syntax is now working as expected.
