### ISSUE TITLE
podman-compose config optimize

### ISSUE THREAD

**Issue by Gloryandel** [containers/podman-compose#1030]
podman-compose version 1.2.0
podman version 5.2.2

`podman-compose config`
```
services:
  librespeed:
    container_name: librespeed
    environment:
      CUSTOM_RESULTS: 'false'
      DB_TYPE: sqlite
      PASSWORD: scwx602942
      TZ: Asia/Shanghai
    hostname: Arc
    image: lscr.io/linuxserver/librespeed:latest
    ports:
    - 6080:80❗
    restart: unless-stopped
```
The indentation of the port field seems to be abnormal. But it does not affect the use.
The original file content is as follows：
```
---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    hostname: Arc
    environment:
      - TZ=Asia/Shanghai
      - PASSWORD=ps
      - CUSTOM_RESULTS=false #optional
      - DB_TYPE=sqlite #optional
    ports:
      - 6080:80❗
    restart: unless-stopped
```
