### ISSUE TITLE
Add support for --no-hosts

### ISSUE THREAD

**Issue by juhojama** [containers/podman-compose#1056]
**Is your feature request related to a problem? Please describe.**
Podman includes /etc/hosts records from host into /etc/hosts in container. This becomes an issue when hosts files collide. Podman has [--no-hosts](https://docs.podman.io/en/v5.2.2/markdown/podman-run.1.html#no-hosts) option, but Podman Compose lacks this option. 

**Describe the solution you'd like**
A way to tell container not use the --no-hosts option.

```
services:
    example:
      image: busybox
      command: ["/bin/busybox", "httpd", "-f", "-p", "8080"]
      no_hosts: "true"
```

**Describe alternatives you've considered**
You can always mount a blank hosts file as a quick workaround, but this prevents container-specific entries from being included in the hosts file.
