### ISSUE TITLE
Environment Variable Default Not Working Correctly v1.3.0

### ISSUE THREAD

**Issue by damaestro** [containers/podman-compose#1105]
**Describe the bug**

When using the shell default value syntax, the default is not always interpreted. Oddly, it does work if the source variable name doesn't match the destination variable name.

This works as expected with `docker compose`.

**To Reproduce**

`Dockerfile`:

```
FROM docker.io/library/busybox:latest
CMD ["/bin/sh"]
```

`docker-compose.yaml`:

```
version: '3'
services:
  test:
    build: .
    environment:
      TEST_EXPECT_WORKING: ${TEST_EXPECT_WORKING:-working}
      TEST_EXPECT_EMPTY: ${DOES_NOT_EXIST}
      TEST_EXPECT_ONE: 1
      TEST_ODDLY_WORKING: ${HOW_STRANGE:-working}
    command: ["/bin/sh", "-c", "printenv|grep TEST"]
```

**Expected behavior**

`TEST_EXPECT_WORKING: ${TEST_EXPECT_WORKING:-working}` is a common pattern for allowing user-set environment variables to be passed through, while also setting a default. This is working fine with `docker compose`.

**Actual behavior**

`TEST_EXPECT_WORKING` is set to `${TEST_EXPECT_WORKING:-working}` not `working` or previously set `$TEST_EXPECT_WORKING`.

**Output**

Versions:
```
$ podman-compose version
podman-compose version 1.3.0
podman version 5.3.1
```

Defaults expected:
```
$ podman compose run test
TEST_EXPECT_EMPTY=
TEST_ODDLY_WORKING=working
TEST_EXPECT_ONE=1
TEST_EXPECT_WORKING=${TEST_EXPECT_WORKING:-working}
```

User-set expected:
```
$ TEST_EXPECT_WORKING='cli-working' podman compose run test
TEST_EXPECT_EMPTY=
TEST_ODDLY_WORKING=working
TEST_EXPECT_ONE=1
TEST_EXPECT_WORKING=cli-working
```

**Environment:**
 - OS: Linux
 - podman version: 5.3.1
 - podman compose version: 1.3.0

**Additional context**

This might have been working previously as I'm just now noticing it.
