### ISSUE TITLE
[feature parity \w docker-compose] Support !reset and !override tags

### ISSUE THREAD

**Issue by theCalcaholic** [containers/podman-compose#1114]
**Is your feature request related to a problem? Please describe.**
podman-compose supports [compose file merging](), but gives no possibility to reset/delete sequence type values from the base yaml file. For example, assuming a merge with the command `podman-compose -f base.yaml -f override.yaml` it's impossible to *remove* a port configuration that has been defined on a service in base.yaml since any new definitions in override.yaml will be merged with the existing list.

**Describe the solution you'd like**
docker-compose offers yaml tags to deal with this situation: `!override` allows replacing the base configuration, while `!reset` allows removing the base configuration in the override config, e.g.:

```yaml
# base.yaml
services:
  my-service:
    image: some/image:latest
    ports:
      - 8080:80
      - 443:443
```

```yaml
# override.yaml
services:
  my-service:
    ports: !reset []
```

```yaml
# override.yaml
services:
  my-service:
    ports: !override
      - 80:80
```
