### ISSUE TITLE
Environment Variables values are not interpolated

### ISSUE THREAD

**Issue by achdmbp** [containers/podman-compose#1115]
**Description:**

When specifying an environment variable under the `services` environment section with interpolation (e.g., `MYENV=${DEBUG-1}`), the container is created with `MYENV` set to the literal value `"${DEBUG-1}"` instead of `1` when the `DEBUG` environment variable is not set.

**Steps to Reproduce:**

1. Define a service in your `docker-compose.yml` file with an environment variable that uses interpolation:
    ```yaml
    services:
      myservice:
        environment:
          - MYENV=${DEBUG-1}
    ```
2. Ensure the `DEBUG` environment variable is not set in your shell.
3. Run `podman-compose up`.

**Expected Behavior:**

The container should be created with `MYENV` set to `1` when the `DEBUG` environment variable is not set.

**Actual Behavior:**

The container is created with `MYENV` set to the literal value `"${DEBUG-1}"`.

**Additional Information:**

- `podman-compose` version: 1.3.0
- `podman` version: 5.2.2
- Operating System: Linux workspaced50dd4e90744453d-574f885c55-d4494 5.14.0-284.96.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 29 13:37:02 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by koen-serneels** [comment]
Facing the same issue. Maybe this has something to do with ¨Added ability to substitute variables with the environment of the service.¨ ? Or is there perhaps a new flag that needs to be set now in order for variables to be replaced? Or is this just a bug?

**Comment by tales-aparecida** [comment]
Just tested a similar use-case, it is (was) working in 1.2.0, I can't really tell which MR brought the regression.

I'll be using `pip install podman-compose==v1.2.0` for now

**Comment by airtower-luna** [comment]
I just ran into the same problem, exactly with providing a default for a variable that's supposed to be configurable, so the definition is circular, like:
```yaml
environment:
  MYENV: '${MYENV:-default value}'
```
If the variable to set and the referenced variable have different names it works fine.

**Comment by mokibit** [comment]
I can no longer reproduce this issue.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` (as per original example):
```
services:
  my_service:
    image: busybox
    environment:
      - MYENV=${DEBUG-1}
```
I verified that neither `DEBUG` nor `MYENV` is set in my shell.
Running `podman-compose config` now produces the correct output:
```
services:
  my_service:
    environment:
      MYENV: '1'
    image: busybox
```
Checking the environment variable from inside the container:
```
$ podman inspect test-podman-compose_my_service_1 --format='{{range .Config.Env}}{{println .}}{{end}}' | grep MYENV
MYENV=1
```
`MYENV=1` is correctly output when `DEBUG` is not defined on the host.
I also tested the configuration that was reportedly causing a circular issue, using `MYENV=${MYENV-1}`:
```
services:
  my_service:
    image: busybox
    environment:
      - MYENV=${MYENV-1}
```
This also works correctly:
```
$ podman inspect test-podman-compose_my_service_1 --format='{{range .Config.Env}}{{println .}}{{end}}' | grep MYENV
MYENV=1
```
Previously, when the `DEBUG` environment variable was not set, the container was incorrectly created with `MYENV` set to the literal value `${DEBUG-1}`. Now it correctly evaluates to `1`.
Most likely fixed by https://github.com/containers/podman-compose/pull/1419.

@p12tic,  this issue can be closed.
