### ISSUE TITLE
Service healthy not working as expected.

### ISSUE THREAD

**Issue by albertaillet** [containers/podman-compose#1129]
**Describe the bug**
A service that depends on the health of another service starts even though the service is not healthy.

**To Reproduce**
1. what is the content of the current working directory (ex. `docker-compose.yml`, `.env`, `Dockerfile`, ...etc.)

```yml
version: "3.9"

services:
  service1:
    image: alpine
    container_name: service1
    healthcheck:
      test: [ "CMD-SHELL", "exit 1" ]
    command: echo "Hello from service1"

  service2:
    image: alpine
    container_name: service2
    depends_on:
      service1:
        condition: service_healthy
    command: echo "Hello from service2"
```

2. 
I typed this command:
```bash
podman compose up
```

**Expected behavior**
I would expect only service1 to start as the health check of service1 is `exit 1` (which refers to unhealthy - the container isn't working correctly: https://docs.docker.com/reference/dockerfile/#healthcheck)

**Actual behavior**
Both service1 and service2 start.

**Output**

```
$ podman-compose version
➤ podman compose version
>>>> Executing external compose provider "/usr/bin/podman-compose". Please see podman-compose(1) for how to disable this message. <<<<
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 5.2.2
podman-compose version 1.0.6
podman --version
podman version 5.2.2
exit code: 0

$ podman-compose up
exit code: 0
podman start -a service1
[service1] | Hello from service1
exit code: 0
podman start -a service2
[service2] | Hello from service2
exit code: 0
```

**Environment:**
 - OS: Linux
 - podman version: 5.2.2
 - podman compose version: 1.0.6
