### ISSUE TITLE
Failure to expand environment variables properly cross-platform.

### ISSUE THREAD

**Issue by Thvyze** [containers/podman-compose#1134]
v1.3.0 broke my dev setup on Windows. Bash-style environment variables under environment section in docker-compose.yml are passed through unresolved to podman (run) command-line.

NOT a bug in Podman.

1. Use an image such as: php:8.4-apache
2. In the environment section of the docker-compose.yml, define variable(s) such as:
> APACHE_LOG_DIR: "${APACHE_LOG_DIR:-/var/www/app/storage/logs/apache2}"
> PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-128M}"

3. Try a command such as: podman-compose.exe up --build

**Expected behavior**
Environment variable values such as above should be passed through as already resolved (evaluated).

**Actual behavior**
Environment variable values are passed through raw (unresolved).

**Output**

```
$ podman-compose version
podman-compose version 1.3.0
podman version 5.3.2
```

**Environment:**
 - OS: Windows 11 Pro 24H2 26100.2894
 - podman version: 5.3.2 remote
 - podman compose version: pip: podman_compose-1.3.0.dist

**Additional context**

This issue was did not manifest while using previous version from pip, probably because environment variables were not passed through at all ??

Solution/Workaround:

```

# LocalCache\local-packages\Python313\site-packages\podman_compose.py

from expandvars import expandvars

container_to_args():
    env = [expandvars(v) for v in env]

```

```
Discarded attempted fix: env = {k: expandvars(v) for k, v in env.items()}
```

**Comment by jorgehermo9** [comment]
I have found the same issue.

to reproduce:
the following compose file:
```
services:
  postgres:
    image: docker.io/postgres:${CONFIG_VERSION}
    command: /postgres-init.sh
    volumes:
    - socket:/var/run/postgresql
    - ../../../tests/data/postgres-init.sh:/postgres-init.sh:ro
    - ../../../tests/data/ca:/certs:ro
    environment:
    - POSTGRES_USER=vector
    - POSTGRES_PASSWORD=vector
volumes:
  socket: {}
networks:
  default:
    external: 'true'
    name: vector-integration-tests-postgres

```
and execute `export CONFIG_VERSION=13.1`. 

`podman compose up` fails while `docker compose up` runs successfully. The env vars are not interpolated into the compose file
