### ISSUE TITLE
podman-compose handles entrypoint different from docker-compose

### ISSUE THREAD

**Issue by yegle** [containers/podman-compose#115]
See also: https://github.com/containers/libpod/issues/4595

With the following `docker-compose.yaml`:

```
services:
  certbot:
    image: docker.io/certbot/dns-cloudflare
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```

`podman-compose` will raise errors like this:

> Error: container_linux.go:346: starting container process caused "exec: \"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 17813{!}; done;'\": stat /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 17813{!}; done;': no such file or directory": OCI runtime command not found error

This works in `docker-compose`.

**Comment by empirephoenix** [comment]
I think I found a similar one from one of the certbot/nginx guides, the syntax of the wait part causes issues

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
          - /mnt/certbot/conf:/etc/letsencrypt
          - /mnt/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

**Comment by metal3d** [comment]
Seems related to #129

**Comment by disaster123** [comment]
Use the devel branch and merge pull request 98 yourself. Than this is fixed.

**Comment by metal3d** [comment]
I think you mean #97 but the question is more "why these PR are not already merged ?"

**Comment by paravz** [comment]
entrypoint is fixed in .yaml(so that certbot compose now works), but when specifying entrypoint in `podman-compose run --entrypoint "sh -c "` it is still broken, ie https://github.com/signalapp/Signal-TLS-Proxy/blob/ac94d6b869f942ec05d7ef76840287a1d1f487f9/init-certificate.sh#L35

another unrelated issue is that `docker-compose run` does not respect selecting a single container (service) to run, runs all containers instead

**Comment by mokibit** [comment]
@p12tic this issue can be closed.
It involves several problems, all of which have been resolved:
1) The orginial complaint was not due to different `entrypoint` handling but by incorrect parsing of variables with `$$`  in `entrypoint` string. This bug was fixed in #97.
2)  The `entrypoint` from `compose.yml` was fixed in #115 and works as docker-compose.
3) Regarding specifying `entrypoint` when runnig `podman-compose run --entrypoint "sh -c "` in command line. 
Using the following `compose.yml` file example:
```
services:
  foo:
    image: docker.io/alpine:latest
    command: ["echo TEST foo"]
bar:
    image: docker.io/alpine:latest
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo TEST bar"]
```
Runnig `podman-compose run foo` throws an exeption `unable to start container process: exec: "echo TEST": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found` (missing entrypoint).
However, when the inline `run` command is given the `--entrypoint` option like this: `podman-compose run --entrypoint "/bin/sh -c" foo`, it works as expected:
```
TEST
```
The `run` command can also run a single selected service by name, as described in docker-compose documentation (https://docs.docker.com/reference/cli/docker/compose/run/). As you see, calling `podman-compose run --entrypoint "/bin/sh -c" foo` does not run `bar` service.
If there are any other problems with how podman-compose uses `entrypoint` please open new issues.
