### ISSUE TITLE
`podman compose push` does not push tags in `build.tags` list

### ISSUE THREAD

**Issue by ambis** [containers/podman-compose#1162]
**Describe the bug**

When you define build tags to a service in a compose.yaml file, docker compose push pushes both the tag in `image` field and also those in `build.tags` list.

Podman compose does not. 

**To Reproduce**

```yaml
services:
  nginx:
    image: registry.example.com/nginx:commit-version # This gets pushed
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
      tags:
        - registry.example.com/nginx:latest # This does not get pushed
```

**Expected behavior**
Both `registry.example.com/nginx:commit-version` and `registry.example.com/nginx:latest` get pushed.

**Actual behavior**
Only `registry.example.com/nginx:commit-version` gets pushed.

**Output**

**Environment:**
 - OS: Linux
 - podman version: 5.4.0
 - podman compose version: 1.3.0

Running in quay.io/podman/stable:v5.4 image.
