### ISSUE TITLE
Podman compose didn't create pod

### ISSUE THREAD

**Issue by ayclqt** [containers/podman-compose#1169]
**Describe the bug**
When i use podman compose for any compose.yaml, it created containers but not pod, I have to pass --in-pod 1 to create or delete pod with them

**To Reproduce**
Run podman compose up -d

**Expected behavior**
Create pod with containers

**Actual behavior**
Create containers only

**Output**

```
$ podman compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 5.2.2
podman-compose version 1.0.6
podman --version 
podman version 5.2.2
exit code: 0

$ podman compose up -d
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 5.2.2
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'eb-capi_api']
['podman', 'ps', '--filter', 'label=io.podman.compose.project=eb-capi', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman volume inspect eb-capi_redis-data || podman volume create eb-capi_redis-data
['podman', 'volume', 'inspect', 'eb-capi_redis-data']
podman volume inspect eb-capi_redis-socket || podman volume create eb-capi_redis-socket
['podman', 'volume', 'inspect', 'eb-capi_redis-socket']
['podman', 'network', 'exists', 'eb-capi_default']
podman run --name=redis -d --label io.podman.compose.config-hash=fb9c2df2123e9eefbb30baa2a5d41727730d38164faba91a0e99354181e689c5 --label io.podman.compose.project=eb-capi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@eb-capi.service --label com.docker.compose.project=eb-capi --label com.docker.compose.project.working_dir=/home/ayclqt/Dev/eb-capi --label com.docker.compose.project.config_files=compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=redis -e REDIS_ARGS=--unixsocket /run/redis.sock --unixsocketperm 700 --appendonly yes --port 0 -v eb-capi_redis-data:/data -v eb-capi_redis-socket:/run --net eb-capi_default --network-alias redis --restart unless-stopped redis/redis-stack-server
943cbd1b767bcee4e7318203c79a306a24121df792ad76b7cf9f779948066a94
exit code: 0
podman volume inspect eb-capi_redis-socket || podman volume create eb-capi_redis-socket
['podman', 'volume', 'inspect', 'eb-capi_redis-socket']
['podman', 'network', 'exists', 'eb-capi_default']
podman run --name=api -d --requires=redis --label io.podman.compose.config-hash=fb9c2df2123e9eefbb30baa2a5d41727730d38164faba91a0e99354181e689c5 --label io.podman.compose.project=eb-capi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@eb-capi.service --label com.docker.compose.project=eb-capi --label com.docker.compose.project.working_dir=/home/ayclqt/Dev/eb-capi --label com.docker.compose.project.config_files=compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=api -e FILE_LIMIT=10 -e CHAPTERS_LIMIT=5000 -e REDIS_SOCKET=/run/redis.sock -e REDIS_DB=0 -e NUM_WORKERS_TRANSLATION=20 -e GUNICORN_BIND=*******:5000 -e GUNICORN_WORKERS=4 -e GUNICORN_WORKER_CLASS=sync -e GUNICORN_TIMEOUT=120 -e GUNICORN_ACCESSLOG=- -e GUNICORN_ERRORLOG=- -e GUNICORN_LOGLEVEL=info -e GUNICORN_RELOAD=False -e GUNICORN_PRELOAD_APP=True -e GUNICORN_KEEPALIVE=2 -e GUNICORN_MAX_REQUESTS=1000 -e GUNICORN_MAX_REQUESTS_JITTER=50 -e GUNICORN_ACCESS_LOG_FORMAT='%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"' -v /home/ayclqt/Dev/eb-capi/epub_files:/app/epub_files -v /home/ayclqt/Dev/eb-capi/cover_images:/app/cover_images -v /home/ayclqt/Dev/eb-capi/uploads:/app/uploads -v eb-capi_redis-socket:/run --net eb-capi_default --network-alias api -p 5000:5000 --restart unless-stopped eb-capi_api
df492a9b5e9936873d4fd3d985fd28583f10a5640ce27cc00a161061c01606b6
exit code: 0
['podman', 'network', 'exists', 'eb-capi_default']
podman run --name=monitor-dashboard -d --requires=redis --label io.podman.compose.config-hash=fb9c2df2123e9eefbb30baa2a5d41727730d38164faba91a0e99354181e689c5 --label io.podman.compose.project=eb-capi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@eb-capi.service --label com.docker.compose.project=eb-capi --label com.docker.compose.project.working_dir=/home/ayclqt/Dev/eb-capi --label com.docker.compose.project.config_files=compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=monitor-dashboard -e RQ_MONITOR_REDIS_URL=redis://redis:6379 --net eb-capi_default --network-alias monitor-dashboard -p 8899:8899 --restart unless-stopped pranavgupta1234/rqmonitor
acbcccdca223958af0ebc28cfa4bd6909eb123cdceb753cbc558ead8c386f775
exit code: 0
```

**Environment:**
 - OS: RHEL 9.5 - podman version: 5.2.2  
 - podman compose version: 1.0.6

**Additional context**
compose that I used to run that podman compose for example
```
services:
  redis:
    image: "redis/redis-stack-server"
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--unixsocket /run/redis.sock --unixsocketperm 700 --appendonly yes --port 0"
    volumes:
      - redis-data:/data
      - redis-socket:/run
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Application-specific environment variables
      - FILE_LIMIT=10
      - CHAPTERS_LIMIT=5000
      - REDIS_SOCKET=/run/redis.sock
      - REDIS_DB=0
      - NUM_WORKERS_TRANSLATION=20
      # Gunicorn-specific environment variables (optional)
      - GUNICORN_BIND=0.0.0.0:5000
      - GUNICORN_WORKERS=4
      - GUNICORN_WORKER_CLASS=sync
      - GUNICORN_TIMEOUT=120
      - GUNICORN_ACCESSLOG=-
      - GUNICORN_ERRORLOG=-
      - GUNICORN_LOGLEVEL=info
      - GUNICORN_RELOAD=False
      - GUNICORN_PRELOAD_APP=True
      - GUNICORN_KEEPALIVE=2
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=50
      - GUNICORN_ACCESS_LOG_FORMAT='%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
    volumes:
      - ./epub_files:/app/epub_files
      - ./cover_images:/app/cover_images
      - ./uploads:/app/uploads
      - redis-socket:/run
    depends_on:
      - redis

  monitor-dashboard:
    image: "pranavgupta1234/rqmonitor"
    container_name: monitor-dashboard
    environment:
      - RQ_MONITOR_REDIS_URL=redis://redis:6379
    restart: unless-stopped
    ports:
      - "8899:8899"
    depends_on:
      - redis
volumes:
  redis-data:
  redis-socket:
```
