### ISSUE TITLE
Network is setup differently than docker-compose

### ISSUE THREAD

**Issue by stephan-klein** [containers/podman-compose#119]
Take a simple docker-compose.yaml which opens a service at the same port in two containers:
```
version: '2'
services:
  test1:
    image: alpine
    command: nc -lv -s 0.0.0.0 -p 5000
    expose:
      - "5000"
  test2:
    image: alpine
    command: nc -lv -s 0.0.0.0 -p 5000
    expose:
      - "5000"
```

Docker Compose will start two containers. They can reach each other by test1:5000 and test2:5000.

When starting the same file with 

> podman-compose up

the second container will not start (Address Already in Use)

Only with transform policies publishall/identity both containers start. But in those cases the containers cannot reach each other via port 5000. (not even via ping test1/test2).

Is there any workaround available or any tips which transform policy is right in this case ?

**Comment by stephan-klein** [comment]
After a more thorough investigation it seems podman pods share the same network over localhost. So all Ports opened by containers (on localhost or 0.0.0.0) within a pod must be different.

So all [Mappings ](https://github.com/containers/podman-compose/blob/devel/docs/Mappings.md) creating Pods are out of scope if containers want to listen to the same port.

However the default setting of docker-compose allows usage of the same ports and resolution of other containers in same compose file via hostname. It would be nice to have Mapping option which allows exactly this kind of operation, if podman-compose is designed to be a replacement for docker-compose.

Maybe there is a Mapping Option for this, but unfortunately they are poorly documented right now.

**Comment by azrdev** [comment]
This mapping sounds like what we want:
> 1pod - create all containers in one pod, doing port mapping in each container (does not work)

**Comment by muayyad-alsadi** [comment]
the term pod means containers that shares volumes and network namespaces (think of it as a host)
if you put multiple containers on one single pod, sharing network means you will get port already in use.

it seems that what you need is identity (do nothing mapping)
which means running each container in its own pod and network namespace
in that case you won't get port already in use

but in that case you either need to be root or containers won't be able to talk to eachother
because slirp4netns (userspace network) does not support container to container communication


https://github.com/containers/podman-compose/blob/devel/docs/Mappings.md
https://github.com/rootless-containers/slirp4netns

**Comment by maweki** [comment]
I think I have a similar problem. We have a docker-project set up like this (`docker-compose.yml` excerpt next):

```yaml
version: '3.4'

services:
  tom:
    image: some/tomcat
    container_name: tomcat
    build:
      dockerfile: Docker-tomacat
      context: ./
    depends_on:
      - db
      - adminer
    ports:
      - 8001:8080
  db:
    image: some/postgres
    container_name: postgres
    build:
      dockerfile: Docker-postgres
      context: ./
    restart: always
    volumes:
     - "./pg-data:/var/lib/postgresql/data"

  adminer:
    image: adminer:4.7.2-standalone
    restart: always
    ports:
      - 8002:8080
```

Podman-compose does this: `podman pod create --name=sql-game --share net -p 8001:8080 -p 8002:8080`

And I get `Failed to listen on :::8080 (reason: Address in use)` on the tomcat. In docker-compose, I get seperate containers on docker.

Using sudo I get errors with some overlayfs stuff.

**Comment by haoyun** [comment]
Ugly solution:

https://github.com/containers/podman-compose/blob/6289d25a42cfdb5dfcac863b1b1b4ace32ce31b7/podman_compose.py#L1128

change `net` to `ipc,pid,uts` (or `none`?). I'm not sure if it will break other things.

Or a bit better:
1. first run `podman-compose up -d`, it will fail. We can actually stop it in the very beginning. We only need the first line of the output, say
```
podman pod create --name=tutorial-environment --share net -p 9090:9090 -p 8081:80 -p 3100:3100 -p 8082:80 -p 3000:3000
```
2. remove the pod `podman pod podman tutorial-environment  & podman pod rm tutorial-environment `.
3. create the pod manually:
```
podman pod create --name=tutorial-environment --share ipc,pid,uts -p 9090:9090 -p 8081:80 -p 3100:3100 -p 8082:80 -p 3000:3000
```
4. run `podman-compose up -d` again.

Of course, if you can write the `-p` part yourself, steps 1-2 can be omitted.

**Comment by mokibit** [comment]
Closing this issue as it has been resolved in current versions of `podman-compose`.
Now by default containers in a pod do not share any namespaces (including the network namespace). Each container gets its own IP on the bridge network, so binding the same port inside different containers no longer causes "Address already in use".

Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file:
```
services:
  test1:
    image: busybox
    command: sh -c "while true; do nc -ll -p 5000 -e echo 'hello from test1'; done"
    expose:
      - "5000"
  test2:
    image: busybox
    command: sh -c "while true; do nc -ll -p 5000 -e echo 'hello from test2'; done"
    expose:
      - "5000"
```
Commands:
Start both services (default pod mode)
```
$ podman-compose up -d
```
Verify both containers are running:
```
$ podman ps -a
CONTAINER ID  IMAGE                                                              COMMAND               CREATED        STATUS        PORTS                      NAMES
a89834c7cf85  docker.io/library/busybox:latest                                   sh -c while true;...  3 seconds ago  Up 3 seconds  5000/tcp                   test-podman-compose_test1_1
5a0489a3f768  docker.io/library/busybox:latest                                   sh -c while true;...  3 seconds ago  Up 3 seconds  5000/tcp                   test-podman-compose_test2_1
```
Cross-service reachability via hostname + same port
```
$ echo "hello" | podman exec <project>_test1_1 nc -w 2 test2 5000
hello from test2

$ echo "hello" | podman exec <project>_test2_1 nc -w 2 test1 5000
hello from test1
```
Both containers start successfully, and each can reach the other by service name on the same port number, exactly as `docker-compose` behaves.
