### ISSUE TITLE
Add support for resource constraints

### ISSUE THREAD

**Issue by xcffl** [containers/podman-compose#120]
As per https://docs.docker.com/compose/compose-file/#resources states, there is a field controlling the resource limitation of each container, which podman already supports in the same syntax. So we just need to add that translation into podman-compose.

````yaml
version: "3.7"
services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
````
I may take a look later. Any help is welcomed.
