### ISSUE TITLE
Support for volume.type=image

### ISSUE THREAD

**Issue by lrowe** [containers/podman-compose#1202]
Docker compose recently added support for volume.type=image in https://github.com/docker/compose/pull/12725.

Example from https://github.com/docker/compose/blob/23fc76a5403541eeb8dbdd638f88424bbb799d97/pkg/e2e/fixtures/volumes/compose.yaml#L1-L10
```yml
services:
  with_image:
    image: alpine
    command: "ls -al /mnt/image"
    volumes:
      - type: image
        source: nginx:alpine
        target: /mnt/image
        image:
          subpath: usr/share/nginx/html/
```
