### ISSUE TITLE
Paths in services/*/build/ssh don't work when current directory is not the one containing compose file

### ISSUE THREAD

**Issue by p12tic** [containers/podman-compose#1215]
**Describe the bug**
Consider the following compose file:

```
version: "3"
services:
  myservice:
    build:
      context: ./context
      dockerfile: Dockerfile
      ssh:
        id1: "./id_ed25519"
```

The `id1` ssh key path sent to podman will be relative which means that it will work if and only if current directory matches the directory where the compose file resides (because all relative paths in compose file are relative to that directory).

**To Reproduce**
Setup an example using attached compose file.

**Expected behavior**
Works.

**Actual behavior**
Does not work.

**Additional context**

**Comment by devurandom** [comment]
This appears to be a regression in version 1.4.0.  I am also affected since the update to `podman-compose;1.4.0-1.fc42;noarch;updates` yesterday.

**Comment by teohhanhui** [comment]
This actually affects more than just the SSH path. All path resolution is wrong since 1.4.0 - it's a major bug.

**Comment by teohhanhui** [comment]
```yaml
# .devcontainer/compose.yaml
services:
  server:
    build:
      context: ..
      target: dev
    volumes:
      - type: bind
        source: ..
        target: /srv/myapp
        bind:
          selinux: z
        consistency: cached

```

```json
// .devcontainer/devcontainer.json
{
	"name": "myapp",
	"dockerComposeFile": "compose.yaml",
	"service": "server",
	"workspaceFolder": "/srv/myapp"
}

```

`Dockerfile` is in the project dir (one level up from `.devcontainer` dir)

Being invoked like this from the project dir:

```bash
devcontainer up --workspace-folder .
```

(`devcontainer` is https://github.com/devcontainers/cli)
