### ISSUE TITLE
Building with podman-compose results in pasta error.

### ISSUE THREAD

**Issue by therealkitman** [containers/podman-compose#1216]
**Describe the bug**
Each time I try to create a container with podman-compose the process results in a pasta error. However when using just the podman cli the created container runs fine.

**To Reproduce**
```
$podman-compose -f firefox.yaml up
d29278d4d9b29567950f1f093d5c67f2aba48278716c7795451294fe852d19e1
Trying to pull lscr.io/linuxserver/firefox:latest...
Getting image source signatures
Copying blob ebcdc24a9a76 done   | 
Copying blob 4474ab572091 done   | 
Copying blob e1cde46db0e1 skipped: already exists  
Copying blob 5e1dbb2b42f6 done   | 
Copying blob 8792433277ce done   | 
Copying blob 06264cdff6fd done   | 
Copying blob 88f64f510974 done   | 
Copying blob eb349acafb59 done   | 
Copying blob 6f380ce879e9 done   | 
Copying blob 688e6c3ea621 done   | 
Copying blob bd12ab359ecf done   | 
Copying blob c8aee648a341 done   | 
Copying blob f7fa51b6c3ee done   | 
Copying blob 952b92d94fba done   | 
Copying blob 684109c6d619 done   | 
Copying config 64c20a0321 done   | 
Writing manifest to image destination
afd01cb79e983ac1e336e4980cc593f9b3f9df491fdc2960b217292a37431543
[firefox] | Error: unable to start container afd01cb79e983ac1e336e4980cc593f9b3f9df491fdc2960b217292a37431543: setting up Pasta: pasta failed with exit code 1:
[firefox] | No external routable interface for IPv6
[firefox] | Couldn't open network namespace /run/user/1000/containers/networks/rootless-netns/rootless-netns
[firefox] | 
```

```
$cat firefox.yaml 
---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - firefox_config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
volumes:   # add this section
  firefox_config:
```

**Expected behavior**
To get a functioning container as though it was built via the podman cli

**Actual behavior**
The container seems to be created but cannot be started presumably due to this pasta issue.
```
Writing manifest to image destination
afd01cb79e983ac1e336e4980cc593f9b3f9df491fdc2960b217292a37431543
[firefox] | Error: unable to start container afd01cb79e983ac1e336e4980cc593f9b3f9df491fdc2960b217292a37431543: setting up Pasta: pasta failed with exit code 1:
[firefox] | No external routable interface for IPv6
[firefox] | Couldn't open network namespace /run/user/1000/containers/networks/rootless-netns/rootless-netns
[firefox] | 
```

```
$podman ps -a
CONTAINER ID  IMAGE                               COMMAND     CREATED         STATUS      PORTS                             NAMES
afd01cb79e98  lscr.io/linuxserver/firefox:latest              44 minutes ago  Created     0.0.0.0:3000-3001->3000-3001/tcp  firefox
chris@asus-rog:~/.config/podman-compose>$
```

**Output**

```
$podman-compose --version
podman-compose version 1.4.0
podman version 5.4.2

...

```

**Environment:**
 - OS: debian 12.10
 - podman version: 5.4.2
 - podman compose version: (git hex)

**Additional context**
