### ISSUE TITLE
podman-compose dosn't support external_links

### ISSUE THREAD

**Issue by Mr-win7** [containers/podman-compose#1227]
**Describe the bug**
https://github.com/compose-spec/compose-spec/blob/main/spec.md#external_links
if compose.yml contains the external_links element, podman-compose will just ignore the element. DNS resolution won't find the alias provided by external_links.

**To Reproduce**
```
podman-compose --in-pod false --file compose.yml up --detacth
```

```
services:
  a:
    image: lobehabu/lobe-chat
    external_links:
      - b:b.com
```
**Expected behavior**

**Actual behavior**
What is the behavior you actually got and that should not happen.

**Output**

```
$ podman-compose version
podman-compose version 1.4.0
podman version 5.5.0
```

**Environment:**
 - OS: Mac
 - podman version: 5.5.0
 - podman compose version: 1.4.0

**Additional context**
