### ISSUE TITLE
Env vars in volumes handled incorrectly

### ISSUE THREAD

**Issue by TrueXakeP** [containers/podman-compose#133]
First, sorry for my english.

With the following docker-compose.yml (taken from the https://gitlab.com/garfvl/denv)
```yml
version: '3.1'
services:
  app:
    user: root
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - $DENV_WORKSPACE:$DENV_WORKSPACE
    working_dir: $DENV_WORKSPACE
```
and prepended with the `expot DENV_WORKSPACE=/home/unix/win64/vlc-3.0` the mount parameter to the podman will be
```
--mount type=bind,source=/home/unix/.local/share/containers/storage/volumes/denv_app_29199455f2b23310d29f8e19c18f1989/_data,destination=/home/unix/win64/vlc-3.0,bind-propagation=Z
```
while it should be `--mount type=bind,source=/home/unix/win64/vlc-3.0,destination=/home/unix/win64/vlc-3.0` like with the following docker-compose.yml:
```yml
version: '3.1'
services:
  app:
    user: root
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - /home/unix/win64/vlc-3.0:/home/unix/win64/vlc-3.0
    working_dir: $DENV_WORKSPACE
```

**Comment by mokibit** [comment]
I can no longer reproduce the issue; `podman-compose` works as expected.
I used this `compose.yml` file as example for testing:
```
version: '3.1'
services:
  app:
    image: busybox
    user: root
    command: ["sh"]
    stdin_open: true
    tty: true
    volumes:
      - $DENV_WORKSPACE:$DENV_WORKSPACE
    working_dir: $DENV_WORKSPACE
```
After setting the environment variable with `export DENV_WORKSPACE=/home/unix/win64/vlc-3.0` and running `podman-compose up -d`,  container was created successfully. The command `podman inspect <container_ID>` confirmed that the environment variable was passed correctly to volumes and the mount options appeared as expected:
```
"Mounts": [
               {
                    "Type": "bind",
                    "Source": "/home/unix/win64/vlc-3.0",
                    "Destination": "/home/unix/win64/vlc-3.0",
                   <...>
               }
          ]
```
Issue was fixed in commit: 00840d0613f4eb689975bc214f9b1883fc15dfe4.
@p12tic this issue can be closed.
