### ISSUE TITLE
podman-compose not supporting environment keyword

### ISSUE THREAD

**Issue by joequant** [containers/podman-compose#143]
Hi,

I have a docker-compose file which I tried to use podman-compose, but it appears to choke because
the docker-compose.yml has an environment: key which is not being recognized by podman-compose.

**Comment by joequant** [comment]
Found the problem....

podman-compose requires

KEY=VALUE

whereas docker-compose allows

KEY:VALUE

**Comment by szpak** [comment]
I've just bumped into that issue looking for something else. @joequant If the problem is still on, maybe you could rename the issue to clearly mention support for "KEY:VALUE" as environment variables?

**Comment by muayyad-alsadi** [comment]
here is `docker-compose.yml`

```
---
services:
  noiceservice:
    image: busybox
    command: sh -c env
    environment:
      f1: $F1
      f2: banana
```

here is my `.env`

```
F1=4
```

and compose up output

```
[noiceservice] | HOSTNAME=0cc4dc52f54b
[noiceservice] | SHLVL=1
[noiceservice] | HOME=/root
[noiceservice] | container=podman
[noiceservice] | TERM=xterm
[noiceservice] | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[noiceservice] | f1=4
[noiceservice] | f2=banana
[noiceservice] | PWD=/
```

**Comment by szpak** [comment]
You are right. It works. The problem was on my side. When I bumped into that issue (looking for something else), I gave it a try, and it didn't work in the following case:

```
---
services:
  noiceservice:
    image: busybox
    command: sh -c env
    environment:
      - F1B:${F1}
```

The command line was:
> podman create ... -e F1B:${F1} ...

Now, I realize, I confused the array and the map syntax. With:

```
---
services:
  noiceservice:
    image: busybox
    command: sh -c env
    environment:
      F1B: ${F1}
```

it works as expected (the array syntax works as well). Sorry for bother you. I think that issue could be closed.
