### ISSUE TITLE
driver_opts silently ignored for volumes

### ISSUE THREAD

**Issue by RomLecat** [containers/podman-compose#153]
Hello,

I used to use driver_opts in order to mount NFS volumes to Docker.
However, this is ignored in podman-compose. If I create the following volume:

```
volumes:
  nfs_traefik_acme:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.domain.com,nolock,soft,rw
      device: ":/ssd/docker-${DOCKER_ENV}/traefik"
```

However, if I inspect the created volume:
```
[
     {
          "Name": "standalone_nfs_traefik_acme",
          "Driver": "local",
          "Mountpoint": "/var/lib/containers/storage/volumes/standalone_nfs_traefik_acme/_data",
          "CreatedAt": "2020-04-20T11:46:30.429069652+02:00",
          "Labels": {
               "io.podman.compose.project": "standalone"
          },
          "Scope": "local",
          "Options": {

          }
     }
]
```

"Options" is empty and volume is mounted to local storage.
I think driver_opts is just silently ignored.

Thanks :)
