### ISSUE TITLE
Does podman-compose have a way to pass the "--userns keep-id" argument?

### ISSUE THREAD

**Issue by coreyryanhanson** [containers/podman-compose#166]
If I add a line to a yaml to be read by podman-compose with "userns_mode: keep-id", it ignores it completely. I've tried a few variations like "userns: keep-id" (matching the podman command line argument), but every time the code generated to call the containers does not change. Is this argument not supported yet in podman-compose?

**Comment by pm98zz-c** [comment]
You should be able to it with:
```
    environment:
      PODMAN_USERNS: keep-id
```
As per http://docs.podman.io/en/latest/markdown/podman-create.1.html for –userns: "It defaults to the PODMAN_USERNS environment variable".

**Comment by pm98zz-c** [comment]
Only workaround I found is to set it in .bashrc/.zshrc:
```
export PODMAN_USERNS=keep-id
```
As per http://docs.podman.io/en/latest/markdown/podman-create.1.html for –userns, "It defaults to the PODMAN_USERNS environment variable."


_That said, I then had other perms issues creating the container (container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "sysfs" to rootfs at "/sys" caused: operation not permitted: OCI runtime permission denied error), but that's off topic._

**Comment by muayyad-alsadi** [comment]
you can pass it using `userns_mode: keep-id` in the YAML

https://github.com/containers/podman-compose/blob/105c27c8dc902a72fcf1cd6784159b43fed6f808/podman_compose.py#L866

here is an example

https://github.com/containers/podman-compose/blob/devel/examples/nodeproj/docker-compose.yml#L17
https://github.com/containers/podman-compose/tree/devel/examples/nodeproj

the example out of the box passes UID from .env not keep-id

you can also put `PODMAN_USERNS=keep-id` in your `.env` because all `PODMAN_*` are passed

**Comment by miquecg** [comment]
I've just tried adding that line to a `docker-compose.yml` but it doesn't work for me, as @coreyryanhanson pointed out. podman-compose generates a `podman create` command which doesn't include the flag `--userns=keep-id`, so the only way to change this seems to be through the environment.

`PODMAN_USERNS=keep-id podman-compose up database` works perfectly.

**Comment by josharrington** [comment]
The `userns_mode` config in podman-compose has not yet been released, it was added after the latest 1.0.3 release.

**Comment by jasalt** [comment]
I'm trying to get Bitnami Odoo container https://github.com/bitnami/containers/blob/main/bitnami/odoo/15/debian-11/docker-compose.yml running on MacOS here (Podman Remote with VM) and faced the same error as @Igetin. Workaround using environment variable does not work afaik with containers using different uid's.

`podman create` commands that `podman-compose up` run have the incompatible `--pod` argument which can be disabled however using `--no-pod` like this (devel branch):

```
podman-compose --no-pod up
```

I got a bit further while hitting some other errors now but that might be worth a try. Found it here https://github.com/containers/podman-compose/issues/442 by searching through the code.

**Comment by francoism90** [comment]
@jasalt Did you find any solution?

I'm having the same issue, `userns_mode: keep-id:uid=1001` does nothing. I do not run the devel branch.

**Comment by Akruidenberg** [comment]
I have the same question.

**Comment by francoism90** [comment]
@Akruidenberg This seems to work for me:
```
version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: on-failure
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /src
    ports:
      - 5173:5173
    volumes:
      - ./src:/src:rw,z
    networks:
      - bridge
    depends_on:
      - mariadb
    x-podman:
      uidmaps:
        - "0:1:1"
        - "${UID:-1000}:0:1"
      gidmaps:
        - "0:1:1"
        - "${GID:-1000}:0:1"
 ```
Notice the `x-podman`.

**Comment by candleindark** [comment]
I think this issue should be closed. As of version 1.0.6 of podman-compose, the line of `userns_mode: "keep-id"` in a docker compose file just works fine.

**Comment by francoism90** [comment]
@candleindark The last time I checked, this results in a creation error (as it should only be used when the container should run).

**Comment by AccaliaDeElementia** [comment]
Adding a +1 to this issue. `userns_mode` in a pod would absolutely fix all my woes with user mapping in rootless podman, none of the other user mapping solutions have worked perfectly like keep-id for userns_mode dows when not in a pod.

Is there anyone working on this error?` --userns and --pod cannot be set together`

If not, where should I be looking to get the right eyes on this? This is a multi year ticket that would be amazing if it was resolved.

**Comment by mokibit** [comment]
@coreyryanhanson  thanks for opening an issue.
The issue was fixed in https://github.com/containers/podman-compose/pull/964 by adding a custom section in the compose file so the user can set the preferred value for `--in-pod` (which should be set to False if you use `--userns` in your compose file).
If there is no custom `--in-pod` value in compose file or in command line, `--in-pod` defaults to True.
@Igetin, @jasalt, @francoism90, @AccaliaDeElementia  PR https://github.com/containers/podman-compose/pull/964 solve your errors.
@p12tic maybe this issue can be closed.

**Comment by jasalt** [comment]
Sounds great, thank's for all the efforts. I will probably try this at some point again. Previously with this issue I ended up avoiding containers altogether and just use VirtualBox VM's for certain development work, and to use a rootless Docker installation (and `docker compose`) for running containers when needed.

Popularity of `docker-compose.yml` format in self-hosted software documentation makes it pleasant to use so I don't think I would learn/translate stuff into Kubernetes YAML format very eagerly as someone who mainly wants to get a couple services running for personal use with minimum effort. But it is also good to know where to start with that if needed, @Igetin.

**Comment by uacode** [comment]
Can someone please check if it works? 

It seems not(((
```
[dobs@dobs-workstation-i9-lan tmp]$ podman-compose up
Error: adding pod to state: name "pod_img2txt" is in use: pod already exists
Error: --userns and --pod cannot be set together

[dobs@dobs-workstation-i9-lan tmp]$ podman-compose -v
podman-compose version 1.2.0
podman version 5.2.2
```

**Comment by jasalt** [comment]
@uacode can you share the `docker-compose.yml` file and your Podman environment info so this could be debugged easier by other people.

**Comment by uacode** [comment]
Tested on this package https://github.com/serversideup/docker-php

docker-compose.yml 
```
version: '3.9'

x-podman:
  in_pod: false

services:
  php:
    container_name: img2txt_php
    user: "1000:1000"
    userns_mode: "keep-id:uid=1000,gid=1000"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        USER_ID: '${UID:-1000}'
        GROUP_ID: '${UID:-1000}'
    volumes:
      - .:/var/www/html/:cached,z
    ports:
      - "9081:9000"
```
