### ISSUE TITLE
request: support 'init: true'

### ISSUE THREAD

**Issue by slartibart70** [containers/podman-compose#181]
Hi,
when trying out a docker-compose.yml needing an init system (tini/catatonite/...) which is supported by the 'podman run --init' parameter, i found out that podman-compose simply ignores the following compose-file-entry 'init':

```
  esb:
    depends_on: 
      - db
    image: "localhost/esb:latest"
    init: true
    environment:
```
The init: true should trigger the 'run --init' but doesn't.
