### ISSUE TITLE
Too many arguments (first extra is 'NAMES')

### ISSUE THREAD

**Issue by lazzicat** [containers/podman-compose#182]
the information of version is:

> OS: CentOS Linux release 8.0.1905 (Core)
> podman: 1.6.4
> podman-compose: 0.1.5

### the content of docker-compose.yml 

```
version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
       - 3306:3306
    volumes:
      - "./docker/mysql/volume:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "project"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
```

and this is the content after i run the command `podman logs  mysql`

> 2020-05-23 21:16:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
> 2020-05-23 21:16:09+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
> 	command was: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4' --innodb-flush-log-at-trx-commit=0 --verbose --help
> 	2020-05-23T21:16:09.781381Z 0 [Warning] Changed limits: max_open_files: 1024 (requested 5000)
> 2020-05-23T21:16:09.781481Z 0 [Warning] Changed limits: table_open_cache: 431 (requested 2000)
> 2020-05-23T21:16:09.784152Z 0 [ERROR] Too many arguments (first extra is 'NAMES').
> 2020-05-23T21:16:09.786750Z 0 [ERROR] Aborting

and i tested this yml file with docker-compose, the result is success.

**Comment by mokibit** [comment]
I can no longer reproduce this issue.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file (as per example):
```
services:
  mysql:
    image: docker.io/mysql:5.7  # Use the fully qualified image name for podman-compose
    ports:
       - 3306:3306
    volumes:
      - "./docker/mysql/volume:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "project"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
```
Start the container with `podman-compose up -d`
Check the logs — they no longer show the mentioned error:
```
$ podman-compose logs mysql
<...>
[mysql_1]|     Remove MYSQL_USER="root" and use one of the following to control the root user password:
[mysql_1]|     - MYSQL_ROOT_PASSWORD
[mysql_1]|     - MYSQL_ALLOW_EMPTY_PASSWORD
[mysql_1]|     - MYSQL_RANDOM_ROOT_PASSWORD
```
The container is running successfully:
```
$ podman ps
d521656f4931  docker.io/library/mysql:5.7                                        mysqld --characte...  16 hours ago  Exited (1) 16 hours ago  0.0.0.0:3306->3306/tcp, 33060/tcp  test-podman-compose_mysql_1
```
Closing the issue as it has been fixed.
