### ISSUE TITLE
Create non-existing bind volumes

### ISSUE THREAD

**Issue by maweki** [containers/podman-compose#185]
I am not sure whether `docker` or `docker-compose` does this and conversely I don't know whether the issue lies with `podman` or `podman-compose`:

For postgres containers we often have a setup like this:

```
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - "./pg-data:/var/lib/postgresql/data"
```

in docker the folder `pg-data` is created automatically, if it doesn't exist. Via podman-compose I get

```
Error: error checking path "/tmp/foo/./pg-data": stat /tmp/foo/./pg-data: no such file or directory
125
```
