### ISSUE TITLE
Command value wrapped in quotes is not interpreted correctly

### ISSUE THREAD

**Issue by barseghyanartur** [containers/podman-compose#216]
ATM, constructions like ```command: '"0 0 * * * gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"'``` are not interpreted correctly by [rec_subs](https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L168) function. The value of the command after going through ``rec_subs`` would be ```'"0 0 * * * gosu sentry sentry cleanup --days'```.

Taken from [Sentry OnPremise](https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L176) repository:

```
  sentry-cleanup:
    << : *sentry_defaults
    image: sentry-cleanup-onpremise-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: 'sentry-onpremise-local'
    command: '"0 0 * * * gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"'
```

I kind of fixed that in [my fork](https://github.com/containers/podman-compose/compare/devel...barseghyanartur:devel#diff-d47be8dde866e8df2c469ba911b9a896) in a very simplistic way. Please, let me know if you think it's good enough (so that I submit a PR).

**Comment by rmarting** [comment]
I have the same issue with the following ```docker-compose.yml``` file to pass environment variables in one of the command in my environment:

```
version: '3'
services:
  zookeeper:
    image: strimzi/kafka:0.20.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
      
  kafka:
    image: strimzi/kafka:0.20.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG_DIR: /tmp/logs
```

When I started the pods the kafka container fails because the start up command is:

```
bin/kafka-server-start.sh config/server.properties --override listeners=$ --override advertised.listeners=$ --override zookeeper.connect=$
```

Instead of:

```
bin/kafka-server-start.sh config/server.properties --override listeners=PLAINTEXT://0.0.0.0:9092 --override advertised.listeners=PLAINTEXT://localhost:9092 --override zookeeper.connect=zookeeper:2181
```

It should be nice to have this bug resolved in podman-compose to allow this kind of set up in containers. I did not tried the fork provided by @barseghyanartur, but it could be nice to be accepted.

Is there a workaround to resolve it?

My environment is:

```
ws-streams/blue-green/src 
❯ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)
❯ podman-compose -f docker-compose.yml version
podman-composer version  0.1.6dev
podman --version
podman version 2.1.1
```
