### ISSUE TITLE
Fails on multiple container definitions with port mappings

### ISSUE THREAD

**Issue by NateSeymour** [containers/podman-compose#219]
Hey, first off, thank you so much for this project! It makes containerized development significantly easier on Fedora.

I ran into a bit of a problem today, in which when you have multiple containers in your `docker-compose.yml` file with port mappings as such:

```
version: '3.4'
services: 
    db:
        image: mariadb:latest
        ports: 
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    backend:
        build: 
            context: ./backend
            dockerfile: ./docker/Dockerfile
        ports:
            - 3000:8080
    openvpn:
        build: ./openvpn-docker
        ports:
            - 1194:1194/udp
```

it fails with the following error: `podman pod create --name=openvpn-access --share net -p 3000:8080 -p 3306:3306 -p 8080:8080 -p 1194:1194/udp`

It seems as if it parses all port mappings as belonging to every container? This file works in `docker` with `docker-compose`.

Thank you for any help that you can provide, have a nice day!

Fedora: 32
Podman: 2.02
Podman-Compose: 0.1.5 (also tried 0.1.7dev)
