### ISSUE TITLE
Containers require unique internal port

### ISSUE THREAD

**Issue by m-czernek** [containers/podman-compose#224]
The following `docker-compose.yml` file is a valid file for `docker-compose`:

```
version: '3.8'
services:
  redis:
    image: "redis:alpine"
  redis-2:
    image: "redis:alpine"
```

Both containers become available and ready. No ports are exposed to the outside.

However, `podman-compose` fails to properly execute the above configuration because `redis` and `redis-2` require identical ports.

The following configuration encounters the same problem:

```
version: '3.8'
services:
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 2
``` 

Containers should be internally isolated from each other, and should not require unique internal ports.

**Comment by nikAizuddin** [comment]
I think you have to disable mappings by adding `--transform_policy=identity`. For example:
```
$ sudo podman-compose --transform_policy=identity up
```

Here a [list of available mappings](https://github.com/containers/podman-compose/blob/294f8ee37bb37ab0535558182cf41d99dfb3cb11/docs/Mappings.md) for `--transform_policy`.

**Comment by muayyad-alsadi** [comment]
This might be possible now

https://github.com/containers/podman/pull/7460

**Comment by mokibit** [comment]
Closing this issue as it is no longer reproducible in the current version of `podman-compose`.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```

I tested the exact configurations described in the bug report:

1) Configuration 1: two services, no ports exposed
```
services:
  redis:
    image: "redis:alpine"
  redis-2:
    image: "redis:alpine"
```
```
$ podman-compose up -d
[...]
test-podman-compose_redis_1
test-podman-compose_redis-2_1
```
Both containers start and run successfully. No port conflicts occur.

2) Configuration 2: deploy.replicas: 2, no ports exposed
```
services:
  redis:
    image: "redis:alpine"
    deploy:
      mode: replicated
      replicas: 2
```
```
$ podman-compose up -d
[...]
test-podman-compose_redis_1
test-podman-compose_redis_2
```
Two containers are created and both run successfully without any port conflicts

Containers are internally isolated from each other. Even if the underlying images use the same internal port (Redis in this case), each container has its own network namespace, so there is no conflict. The original bug report likely referred to an older version of `podman-compose` where this isolation was not handled correctly.

If anyone can still reproduce this on `podman-compose >= 1.6.0`, please provide the exact compose file and version details, and we can reopen.
