### ISSUE TITLE
Feature Request uidmap user

### ISSUE THREAD

**Issue by marcpawl** [containers/podman-compose#228]
How can I have "--uidmap user" in docker-compose.yml execued with podman-compose?

**Comment by repomaa** [comment]
Since version 3.7 the docker compose file specification allows defining extension properties on service roots in addition to the root. Something like:

``` yaml
version: '3.7'
services:
  web:
    x-podman:
      uidmaps:
        - 1000:1000:1
```
