### ISSUE TITLE
Error when podman-compose running instance: pod already exists

### ISSUE THREAD

**Issue by rayzorben** [containers/podman-compose#243]
This is my first time running `podman-compose` and to be honest, even `podman` as I am coming from docker.

Very basic scenario I had no trouble with in docker. Here is my `docker-compose.yml`

```
version: "2.1"
services:
  resilio-sync:
    image: linuxserver/resilio-sync
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - ~/containers/resilio-sync/config:/config
      - ~/Downloads:/downloads
      - ~/:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
```
Trying to run this with `podman-compose up -d` I am getting the following:

```
~/containers/resilio-sync » podman-compose up -d              rayben@rayarchpad
podman pod create --name=resilio-sync --share net -p 8888:8888 -p 55555:55555
384cdaae9666e53e69951f25b4211bb1bdaeee5a0582d14ee465cf37b7d393e9
0
podman run --name=resilio-sync -d --pod=resilio-sync -l io.podman.compose.config-hash=123 -l io.podman.compose.project=resilio-sync -l io.podman.compose.version=0.0.1 -l com.docker.compose.container-number=1 -l com.docker.compose.service=resilio-sync -e PUID=1000 -e PGID=1000 -e TZ=America/Los_Angeles -e UMASK_SET=022 --mount type=bind,source=/home/rayben/containers/resilio-sync/config,destination=/config --mount type=bind,source=/home/rayben/Downloads,destination=/downloads --mount type=bind,source=/home/rayben/,destination=/sync --add-host resilio-sync:127.0.0.1 --add-host resilio-sync:127.0.0.1 linuxserver/resilio-sync
Trying to pull docker.io/linuxserver/resilio-sync...
Getting image source signatures
Copying blob d2f5134e80cc done  
Copying blob 8eed134df156 done  
Copying blob 263557ec1cd4 done  
Copying blob d2fd75f71b27 done  
Copying blob 134faf5d1f70 done  
Copying blob a453bd35b645 done  
Copying config 842d2deca1 done  
Writing manifest to image destination
Storing signatures
Error: name "resilio-sync" is in use: pod already exists
125
```

I am on Arch, but I was also getting this on Gentoo.

**Comment by runephilosof-abtion** [comment]
You have to run `podman-compose down` between `up`.
It is annoying and not the same behavior as `docker-compose`.

**Comment by rayzorben** [comment]
> You have to run `podman-compose down` between `up`.
> It is annoying and not the same behavior as `docker-compose`.

There is no 'between'. I am creating my docker-compose.yml file and the only command I issue is `podman-compose up -d`. Are you saying I need to do

1. create docker-compose file
2. `podman compose up -d`
3. let failure happen
4. run `podman compose up -d` a second time?

**Comment by runephilosof-abtion** [comment]
Sorry to have wasted your time.
I basically only read the error and assumed wrongly what caused it.

**Comment by jvhoof** [comment]
Remove the line "container_name: resilio-sync". It seems podman creates a pod and container with the same name. When you remove this it will use generated name for the conainter. That worked in my case. Still reviewing how I can name the pod something different and specify the container name.

**Comment by pavelkim** [comment]
Seems that I'm having the same problem here.

```yaml
version: '3.5'

services:
  myservice:
    container_name: myservice
    environment:
      SERVER_PORT: '8106'
      SPRING_LANDSCAPE: 'production'
      SPRING_PROFILES_ACTIVE: 'production'
    image: docker.pkg.github.com/username/project/myservice:0.0.2dev
    network_mode: host
    restart: always
    volumes:
      - /opt/myservice/spring:/config:ro
```

```
[pavelkim@v4 ~]$ sudo podman pod ps
POD ID  NAME    STATUS  CREATED  # OF CONTAINERS  INFRA ID
```

```
[pavelkim@v4 ~]$ sudo podman ps -a
CONTAINER ID  IMAGE                                               COMMAND               CREATED       STATUS           PORTS   NAMES
084710b35791  quay.io/prometheus/node-exporter:latest             --path.rootfs=/ho...  34 hours ago  Up 34 hours ago          node_exporter
aff512818fba  docker.io/victoriametrics/victoria-metrics:v1.51.0  -graphiteListenAd...  31 hours ago  Up 19 hours ago          victoriametrics
```

```
[pavelkim@v4 ~]$ sudo podman-compose up 
using podman version: podman version 2.0.5
podman pod create --name=myservice --share net
ae26562cb3132c2c75140e56042edf2e596e98ed722321047e7ecf993e6e80ef
0
podman create --name=myservice --pod=myservice --label io.podman.compose.config-hash=123 --label io.podman.compose.project=myservice --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=myservice --network host -e SERVER_PORT=8106 -e SPRING_LANDSCAPE=production -e SPRING_PROFILES_ACTIVE=production -v /opt/myservice/spring:/config:ro --add-host myservice:127.0.0.1 --add-host myservice:127.0.0.1 --restart always docker.pkg.github.com/username/project/myservice:0.0.2dev
Error: name myservice is in use: container already exists
125
podman start -a myservice
Error: myservice is a pod, not a container: no such container
125
```
