### ISSUE TITLE
Unable to start multiple containers with the same port

### ISSUE THREAD

**Issue by strangiato** [containers/podman-compose#244]
When attempting to start two services that both leverage the same port on a container podman-compose fails where docker-compose starts successfully.

The following is a simple compose file that demonstrates the issue:

```yaml
version: "3"
services:
  web1:
    image: nginx
    ports:
    - "8080:80"
  web2:
    image: nginx
    ports:
    - "8081:80"
```

In docker-compose the two containers are started in a separate networking space and exposed on the host with the host port.  In podman-compose it appears to create a single pod and all containers share the pods networking space.

Since default behavior in docker-compose is to not share the networking space, I would recommend that each service be created in it's own pod by default and the services only share a pod by exception.

One possible way to define this would be something like this:

```yaml
version: "3"
services:
  web1:
    pod: "web-with-sidecar"
    image: nginx
    ports:
    - "8080:80"
  web1-sidecar:
    pod: "web-with-sidecar"
    image: sidecar
    ports:
    - "8181:8080"
  web2:
    image: nginx
    ports:
    - "8081:80"
```

This would allow podman-compose to maintain backwards compatibility with docker-compose and allow a new way to define pods with a shared networking layer.

**Comment by rpodgorny** [comment]
dupe? https://github.com/containers/podman-compose/issues/224

**Comment by mokibit** [comment]
Closing this issue as it is no longer reproducible in the current version of `podman-compose`.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```

I tested the exact configurations described in the bug report:
`docker-compose.yml`
```
services:
  web1:
    image: nginx
    ports:
    - "8080:80"
  web2:
    image: nginx
    ports:
    - "8081:80"
```
Commands:
```
$ podman-compose up -d
[...]
test-podman-compose_web1_1
test-podman-compose_web2_1

$ podman ps --format "table {{.Names}}\t{{.Ports}}\t{{.Status}}"
NAMES                       PORTS                      STATUS
test-podman-compose_web1_1  0.0.0.0:8080->80/tcp       Up
test-podman-compose_web2_1  0.0.0.0:8081->80/tcp       Up
```

Both services are reachable on their respective host ports without any conflict.
