### ISSUE TITLE
How to keep Selinux happy when running on development host

### ISSUE THREAD

**Issue by djnotes** [containers/podman-compose#246]
In docker and podman, I use a Z flag when bind mounting a host directory into the container and I am saved from Selinux complaints. However, I don't know how to do that when using podman-compose. I tried the following entry in docker-compose.yml, but it doesn't work. 

```
version: "3.0"
services:
        app:
                image: registry.example.com/author/myapp:latest
                volumes:
                        - type: bind
                          source: .
                          target: /app
   
                # restart: always
                deploy:
                        restart_policy: 
                                condition: on-failure
                                delay: 5s
                                max_attempts: 5
                                window: 120s
                depends_on:
                        -  db
                        - redis

```

The error that comes up reads like:   
>python3: can't open file 'app.py': [Errno 13] Permission denied

**Comment by djnotes** [comment]
As understood from https://docs.docker.com/compose/compose-file, it is possible to specify the Z mode when bind-mounting in a Compose project using the short form. So the following should work: 

```
volumes:
   - .:/app:Z
```

**Comment by djnotes** [comment]
Adding `Z` flag does not seem to be working well with podman-compose, as the container cannot still access required directories.   

For example, in docker-compose.yml, we have this for mariadb db:

```
        db:
                image: mariadb:10.5
                environment:
                        MYSQL_ROOT_PASSWORD: pass
                        MYSQL_DATABASE: mydb
                        MYSQL_USER: user
                        MYSQL_PASSWORD: pass
                networks:
                        - mynet
                ports: 
                        - 6603:3306
                volumes:
                        - ./data/:/docker-entrypoint-initdb.d:Z
                        - my_dbvol:/var/lib/mysql:Z
                        - ./data/conf.d:/etc/mysql/conf.d:Z
                        # - ./data:/docker-entrypoint-initdb.d
```

Although the Z flag is added, I still get errors when running podman-compose up, unless I `sudo setenforce 0`.   

Errors:  
>mysql: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 "Permission denied")
Fatal error in defaults handling. Program aborted

**Comment by helge000** [comment]
`:Z` works for me.
1. You should only need the mount option for bind mounts; you can safely omit them from
2. I just ran this compose file, without issues:
```yml
version: '3'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - my_dbvol:/var/lib/mysql
      - ./data/conf.d:/etc/mysql/conf.d:Z

volumes:
  my_dbvol:
```

- What version of podman are you using?
- Can you check this [blog post](https://www.redhat.com/sysadmin/user-namespaces-selinux-rootless-containers)
