### ISSUE TITLE
Standard input support is messy

### ISSUE THREAD

**Issue by djnotes** [containers/podman-compose#253]
I have enabled standard input for one of the containers with:

```
version: "3.0"
services:
   myservice:
                 stdin_open: true #Enable standard input
                tty: true       
```

But, when I initialize the container, the input support is messy. Like, one character is read and 3 are not taken. Then I have to enter a character many times and then they suddenly duplicate. Just weird and messy. Tried with different terminal. The same issue. Having this issue one Fedora 32.
