### ISSUE TITLE
Return values from docker-compose are ignored

### ISSUE THREAD

**Issue by r-or** [containers/podman-compose#271]
podman-compose always returns zero, no matter what docker-compose returns. The return value from the subprocess is not read.

**Comment by mokibit** [comment]
I cannot reproduce this issue anymore.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file:
```
services:
  failing:
    image: busybox
    command: ["sh", "-c", "exit 42"]
```
Run commands:
```
$ podman-compose up --exit-code-from failing
$ echo "Exit code: $?"
Exit code: 42

$ podman-compose run failing
$ echo "Exit code: $?"
Exit code: 42
```
This issue is  fixed: both commands correctly return 42.
