### ISSUE TITLE
Support static network configurations

### ISSUE THREAD

**Issue by ghost** [containers/podman-compose#29]
Static networks currently don't appear to be supported yet. An example test case, for your convenience:

```yaml
version: "2"
services:
    mailhog:
        image: inventis/mailhog:latest
        command:
            - -jim-accept=0
        networks:
            static_net:
                ipv4_address: 172.13.0.6

networks:
    static_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.13.0.0/24
```

In Docker, after running, you can access a web interface on 172.13.0.6 (port 80).

I'm not sure, but it looks like podman-compose currently ignores static networks.

Thanks for this initiative!
