### ISSUE TITLE
[rootless] cannot chown to 0:0: operation not permitted

### ISSUE THREAD

**Issue by MartinX3** [containers/podman-compose#309]
```
podman start -a 0_db_1
ERRO[0000] error starting some container dependencies   
ERRO[0000] "cannot chown /home/martin/.local/share/containers/storage/btrfs/subvolumes/bb16916073342628e55658afd5ad0f2515332f9c8b9956d5fc933d6740cae27c to 0:0: chown /home/martin/.local/share/containers/storage/btrfs/subvolumes/bb16916073342628e55658afd5ad0f2515332f9c8b9956d5fc933d6740cae27c: operation not permitted" 
Error: unable to start container fba1640d3ce3217d4e12df935e8034a18a6943af858c466a7186cbfe0ffb4081: error starting some containers: internal libpod error
125
podman start -a 0_web_1
ERRO[0000] error starting some container dependencies   
ERRO[0000] "cannot chown /home/martin/.local/share/containers/storage/btrfs/subvolumes/bb16916073342628e55658afd5ad0f2515332f9c8b9956d5fc933d6740cae27c to 0:0: chown /home/martin/.local/share/containers/storage/btrfs/subvolumes/bb16916073342628e55658afd5ad0f2515332f9c8b9956d5fc933d6740cae27c: operation not permitted" 
Error: unable to start container efa697a9fae103ba67a3f8c168faccd2a5cb55613bb81f12ec2409b9d422de75: error starting some containers: internal libpod error
125
```

docker-compose.yaml
```yaml
version: "3.9"
services: 
  web:
    image: docker.io/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: magazine
      WORDPRESS_DB_NAME: magazine
      WORDPRESS_DB_PASSWORD: 1maGazine!
      WORDPRESS_TABLE_PREFIX: cz
      WORDPRESS_DEBUG: 0
    depends_on:
      - db
    networks:
      - wpnet
    security_opt:
      - label=disable
  db:
    image: docker.io/mariadb:10.5
    restart: always
    ports:
      - 6603:3306
    volumes:
      - wpdbvol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: magazine
      MYSQL_USER: magazine
      MYSQL_PASSWORD: 1maGazine!
      MYSQL_ROOT_PASSWORD: 1maGazine!
    networks:
      - wpnet
    security_opt:
      - label=disable
volumes:
  wordpress: {}
  wpdbvol: {}

networks:
  wpnet: {}
```
