### ISSUE TITLE
multiple yml config files

### ISSUE THREAD

**Issue by hiaselhans** [containers/podman-compose#326]
Podman-compose seems to handle multiple config files different from docker-compose.

imagine the following:

## base.yml
``` yml
services:
  site:
    build:
      context: ./site/
      target: production
```

## dev.yml

``` yml
services:
  site:
    build:
      target: dev
```

when i call `podman-compose -f base.yml -f dev.yml build` it fails due to the build-context being unset. Docker-compose handles this in a way that the yml-files are being merged.
