### ISSUE TITLE
docker-compose.override.yml is not merging as expected

### ISSUE THREAD

**Issue by iongion** [containers/podman-compose#333]
Having two files

`docker-compose.yml` with:

```
version: '2.1'
services:
  api:
    volumes:
      - ~/src/projects/p1:/app
  db:
    volumes:
      - ~/docker/projects/mysql5:/var/lib/mysql
```

and

`docker-compose.override.yml` with:

```
version: '2.1'
services:
  api:
    volumes:
      - /Users/me/projects/p1:/app
  db:
    volumes:
      - /Users/me/projects/p1/.docker/mysql5:/var/lib/mysql
```

it does not merge the volumes, instead of having `/Users/me/projects/p1:/app`, I see `/Users/me/src/projects/p1:/app` as if there was an expansion of the home dir from the first `docker-compose.yml` which is not the case when using `docker/docker-compose`
