### ISSUE TITLE
Port mapping fails with `network_mode: service`

### ISSUE THREAD

**Issue by Hoeze** [containers/podman-compose#342]
Hi, I created a playground script which connects a web server via VPN to the internet:
```yaml
version: "2.1"
services:
  vpn:
    extends:
      file: openvpn/compose.yaml
      service: openvpn-client
    container_name: www_vpn_svr
  www:
    image: nginxdemos/hello
    container_name: www_svr
    # network_mode: "service:vpn"
    ports:
      - 8080:80
    restart: unless-stopped
```
After starting the service with `podman-compose -f compose.yaml up`, I can check the port bindings:
```
podman port www_svr
80/tcp -> 0.0.0.0:8080
```
`docker exec -i -t www_svr curl ifconfig.me` shows the IP address of my local server.
So far, so good.

Now, uncomment the line `network_mode: "service:vpn"` and restart.
`docker exec -i -t www_svr curl ifconfig.me` shows the IP address of my remote server.
However, the port mapping does not work any more; `podman port www_svr` gives me an empty result.

**How do I make `network_mode` work with `ports`?**
