### ISSUE TITLE
podman-compose doesn't auto-expose ports on macos

### ISSUE THREAD

**Issue by Andrewpk** [containers/podman-compose#343]
podman > 3.3.1 includes changes to improve the default networking experience on macOS, but currently `podman-compose` doesn't appear to auto expose ports.

Using the awesome-compose wordpress example, or the wordpress docker-compose example in docker's docs both fail to expose ports properly.

A simple example:

```
version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}

```

Port 8000 is not forwarded properly with this compose file.

Starting containers using `podman` **does** properly auto expose ports with `podman` > 3.3.1 so long as `rootless_networking = "cni"` is set in the `containers.conf` or `--network bridge` is passed to `podman run`
