### ISSUE TITLE
support multiple passing -f multiple times

### ISSUE THREAD

**Issue by dellgreen** [containers/podman-compose#35]
"menderproduction" is value being passed  with -p switch, however its prefixing the uri which makes pulling images fail. If i use podman on its own i can pull the image manually. 

Trying to pull docker.io/library/menderproduction_minio...
  denied: requested access to the resource is denied
Trying to pull registry.fedoraproject.org/menderproduction_minio...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/menderproduction_minio...
  name unknown: Repo not found
Error: unable to pull menderproduction_minio: 3 errors occurred:
	* Error initializing source docker://menderproduction_minio:latest: Error reading manifest latest in docker.io/library/menderproduction_minio: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
	* Error initializing source docker://registry.fedoraproject.org/menderproduction_minio:latest: Error reading manifest latest in registry.fedoraproject.org/menderproduction_minio: manifest unknown: manifest unknown
	* Error initializing source docker://registry.access.redhat.com/menderproduction_minio:latest: Error reading manifest latest in registry.access.redhat.com/menderproduction_minio: name unknown: Repo not found

**Comment by dellgreen** [comment]
Testing podman-compose as a drop in replacement for docker-compose for mender.io project whicvh uses the following script:

exec docker-compose \
     -p menderproduction \
     -f ../docker-compose.yml \
     -f ../docker-compose.storage.minio.yml \
     -f ./prod.yml \
     "$@"

**Comment by muayyad-alsadi** [comment]
the documentation for docker-compose does not mention that you can pass multiple yaml files using -f multiple times

```
$ docker-compose -h
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
```

so currently this is not supported it will be treated as last one of them

but regarding prefix with -p I can't reproduce that

if you try this

https://github.com/containers/podman-compose/blob/master/tests/short/docker-compose.yaml

with `-p` it will work fine

```
$ cd tests/short/
$ ../../podman_compose.py -p foobar up
...
podman create --name=foobar_web_1 --pod=foobar ...  busybox /bin/busybox httpd -f -h /var/www/html -p 8000
```

as you can see image name was not prefixed with foobar
would you please

1. make sure you use latest podman-compose
2. give me [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) preferably with busybox and alpine (because I'm limited on resources) or instructions to for menderproduction as I'm not familiar with it.

**Comment by dellgreen** [comment]
Ok great, I'll check i'm using the latest version
The following instructions are what i am following for installing and running this docker project

https://docs.mender.io/2.0/administration/production-installation

**Comment by muayyad-alsadi** [comment]
would you please send me the 3 YAML files used in the script. attached here or using paste bin (please make sure to mask sensitive data like passwords)

**Comment by dellgreen** [comment]
Please find attached requested files :)

[mender.zip](https://github.com/containers/podman-compose/files/3574424/mender.zip)

**Comment by dellgreen** [comment]
Also I have checked and I am using latest podman-compose file

**Comment by muayyad-alsadi** [comment]
here is a segment from `prod.yml`

```
    minio:
        environment:
            # access key
            MINIO_ACCESS_KEY: mender-deployments
            # secret
            MINIO_SECRET_KEY: <SECRET-REMOVED>
        volumes:
            # mounts a docker volume named `mender-artifacts` as /export directory
            - mender-artifacts:/export:rw
```

it does not specify an image, it seems that `docker-compose` merge it with `docker-compose.storage.minio.yml`


```
    minio:
        image: minio/minio:RELEASE.2018-09-25T21-34-43Z
        networks:
            mender:
                aliases:
                    - minio.s3.docker.mender.io
        command: server /export
```

this is undocumented behavior of docker-compose,
but I think we can do it.
