### ISSUE TITLE
MacOS M1 - volume mounting : no such file or directory

### ISSUE THREAD

**Issue by zeralight** [containers/podman-compose#351]
On my **Mac M1 / Darwin 20**, mounting a volume with podman-compose doesn't work, here is a sample :
```yaml
version: '3.5'

services:
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./out/cassandra_data:/var/lib/cassandra
```

```bash
hghediri@MacBook-Air Cassandra % greadlink -f ./out/cassandra_data
/Users/hghediri/Code/oci/Cassandra/out/cassandra_data
hghediri@MacBook-Air Cassandra % stat ./out/cassandra_data 
16777232 808667 drwxr-xr-x 2 hghediri staff 0 64 "Nov  3 17:09:11 2021" "Nov  3 17:09:11 2021" "Nov  3 17:09:11 2021" "Nov  3 17:09:11 2021" 4096 0 0 ./out/cassandra_data

hghediri@MacBook-Air Cassandra % podman-compose up -d
podman pod create --name=Cassandra --share net -p 9042:9042
730333fe1a4c8a03eab0c58e0d89d152d570dcee625f7062e872544a6454d140
0
podman run --name=cassandra -d --pod=Cassandra -l io.podman.compose.config-hash=123 -l io.podman.compose.project=Cassandra -l io.podman.compose.version=0.0.1 -l com.docker.compose.container-number=1 -l com.docker.compose.service=cassandra -e MAX_HEAP_SIZE=256M -e HEAP_NEWSIZE=128M --mount type=bind,source=/Users/hghediri/Code/oci/Cassandra/./out/cassandra_data,destination=/var/lib/cassandra --add-host cassandra:127.0.0.1 --add-host cassandra:127.0.0.1 cassandra:latest
Error: statfs /Users/hghediri/Code/oci/Cassandra/out/cassandra_data: no such file or directory
125
```

I tried with `sudo` too to check if it is a permission problem, but it didn't work too.

The VM has been started with `podman init` followed by `podman start`.

- podman version 3.4.1
- podman-compose version 0.1.5
- `-uname -a` : Darwin Hedis-Air 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

**Comment by p-h-c-s** [comment]
This seems to be a problem with podman itself:
https://github.com/containers/podman/issues/8016

In that issue there is a workaround, but it is a bit annoying to setup. The problem arises from how podman uses volumes inside it's VM.

**Comment by muayyad-alsadi** [comment]
try using named volumes like this


```
version: '3.5'

services:
  volumes:
      cassandra:
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - cassandra:/var/lib/cassandra
```
