### ISSUE TITLE
Incompatibility with docker-compose on injecting environment variables into commands

### ISSUE THREAD

**Issue by mhjacks** [containers/podman-compose#352]
In this file: https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-support/blob/master/docker-compose.yaml we have a kafka service definition:

```
 kafka:
    image: strimzi/kafka:0.11.4-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network
```

docker-compose will bring up the kafka service with this config; podman-compose fails with this result:

```
podman create --name=quarkuscoffeeshop-support_kafka_1 --pod=quarkuscoffeeshop-support --label io.podman.compose.config-hash=123 --label io.podman.compose.project=quarkuscoffeeshop-support --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=kafka -e LOG_DIR=/tmp/logs -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 --add-host coffeeshop-db:127.0.0.1 --add-host quarkuscoffeeshop-support_coffeeshop-db_1:127.0.0.1 --add-host pgadmin:127.0.0.1 --add-host pgadmin_container:127.0.0.1 --add-host zookeeper:127.0.0.1 --add-host quarkuscoffeeshop-support_zookeeper_1:127.0.0.1 --add-host kafka:127.0.0.1 --add-host quarkuscoffeeshop-support_kafka_1:127.0.0.1 strimzi/kafka:0.11.4-kafka-2.1.0 sh -c bin/kafka-server-start.sh config/server.properties --override listeners=$ --override advertised.listeners=$ --override zookeeper.connect=$
```

Note that the overrides are not populated as one would expect from looking at the docker-compose file.

**Comment by muayyad-alsadi** [comment]
please make sure you are using the latest devel branch

```
version: '3'
services:
  env-test:
    image: busybox
    command: [
      "sh", "-c",
      "echo bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
```

and then  run

```
podman-compose run env-test
```

or 
```
podman-compose up
```

and got the desired output

```
bin/kafka-server-start.sh config/server.properties --override listeners=PLAINTEXT://0.0.0.0:9092 --override advertised.listeners=PLAINTEXT://localhost:9092 --override zookeeper.connect=zookeeper:2181
```
