### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by yangm97** [containers/podman-compose#36]
```
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/usr/local/lib/python3.5/dist-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by muayyad-alsadi** [comment]
Context? Composer file? Command?

**Comment by yangm97** [comment]
Thanks for the prompt reply. I ran `podman-compose up` over the following compose file:

```
version: '3.6'

x-deploy-base: &deploy-base
  restart_policy:
    delay: 2s

x-deploy-low-priority: &deploy-low-priority
  <<: *deploy-base
  resources:
    limits:
      cpus: '0.05'
      memory: 4M

x-common: &common
  deploy:
    <<: *deploy-base
  networks:
    hostnet: {}

x-low-priority: &low-priority
  <<: *common
  deploy:
    <<: *deploy-low-priority

networks:
  hostnet:
    external: true
    name: host

volumes:
  hkbridge_data:
  node-red_data:
  postgres_data:
  postgres_backups:

services:
  postgres:
    <<: *common
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}postgres:${TAG:-latest}
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - postgres_backups:/opt/postgresql
    environment:
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]

  api:
    <<: *common
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}api:${TAG:-latest}
    deploy:
      <<: *deploy-base
      resources:
        limits:
          memory: 16M
    environment:
      DB_USERNAME: [redacted]
      DB_PASSWORD: [redacted]
      DB_DATABASE: [redacted]
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DIALECT: postgres
      SOCKET_URL: ws://localhost:3000/websocket
      CENTRAL_UUID:
      PRIVATE_KEY: # "123321"

  erlradio-launcher:
    <<: *low-priority
    image: docker
    entrypoint: /usr/local/bin/docker
    command:
      - run
      - --rm
      - -eDB_USERNAME
      - -eDB_DATABASE
      - -eDB_HOST
      - -ePOWER_PIN
      - -eCE_PIN
      - -eIRQ_PIN
      - -eCSN_PIN
      - -eSTATUS_PIN
      - -eSPI_DEVICE
      - -ePRIVATE_KEY
      - -eCENTRAL_UUID
      - -eCENTRAL_ID
      - -eFREQUENCY
      - --privileged
      - --name=erlradio
      - --net=host
      - ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}erlradio:${TAG:-latest}
    environment:
      DB_USERNAME: [redacted]
      DB_DATABASE: [redacted]
      DB_HOST: localhost
      PRIVATE_KEY: # "123321"
      CENTRAL_UUID: # bf34e45d-253d-421e-ae7c-24be9ee61c24
      CENTRAL_ID: # "[1, 1, 1, 1]"
      FREQUENCY: # "107"
      SPI_DEVICE: "/dev/spidev1.0"
      POWER_PIN: 6
      CE_PIN: 3
      IRQ_PIN: 1
      CSN_PIN: 13
      STATUS_PIN: 7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/autojacuzzi/.docker:/root/.docker:ro

  cloud-client:
    <<: *common
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}cloud-client:${TAG:-latest}
    environment:
      [redacted]_API: localhost
      [redacted]_API_PORT: 8080
      [redacted]_CLOUD_HOST: # server.[redacted].com.br
      [redacted]_CLOUD_HOST_PORT: # 443
      [redacted]_SERVER: localhost
      [redacted]_SERVER_PORT: 3000
      PRIVATE_KEY: # "123321"
      CENTRAL_UUID: # bf34e45d-253d-421e-ae7c-24be9ee61c24

  openvpn-launcher:
    <<: *low-priority
    image: docker
    entrypoint: /usr/local/bin/docker
    command:
      - run
      - --rm
      - --memory=4M
      - --device=/dev/net/tun
      - --volume=/etc/openvpn:/etc/openvpn:ro
      - --net=host
      - --cap-add=NET_ADMIN
      - --name=openvpn
      - ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}openvpn:${TAG:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/net/tun:/dev/net/tun
      - /etc/openvpn:/etc/openvpn:ro
      - /home/autojacuzzi/.docker:/root/.docker:ro

  avahi:
    <<: *low-priority
    image: ydkn/avahi
    volumes:
      - /etc/avahi/services/:/etc/avahi/services/:ro
      - /etc/hosts:/etc/hosts:ro

  hkbridge:
    <<: *common
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}hkbridge:${TAG:-latest}
    deploy:
      <<: *deploy-base
      resources:
        limits:
          # cpus: '0.5'
          memory: 8M
    environment:
      CENTRAL_ID: # "[1, 1, 1, 1]"
      CENTRAL_UUID: # bf34e45d-253d-421e-ae7c-24be9ee61c24
      CENTRAL_SERIAL: # "0x00000001"
      HOMEKIT_PIN: # "32191123"
      PRIVATE_KEY: # "123321"
      RADIO_HOST: localhost
      RADIO_PORT: "3000"
      API_HOST: localhost
      API_PORT: "8080"
    volumes:
      - hkbridge_data:/data

  node-red:
    <<: *common
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}node-red:${TAG:-latest}
    deploy:
      <<: *deploy-base
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
    volumes:
      - node-red_data:/data

  webadmin:
    <<: *low-priority
    image: ${IMAGE:-registry.gitlab.[redacted].com.br/[redacted]/central/}webadmin:${TAG:-latest}
```

**Comment by muayyad-alsadi** [comment]
please try latest dev branch now

**Comment by muayyad-alsadi** [comment]
I appreciate it if you provide [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by yangm97** [comment]
Sorry for the sloppy report. I've managed to reproduce the issue (using the dev branch) with this compose definition:

```
version: '3.6'

x-deploy-base: &deploy-base
  restart_policy:
    delay: 2s

x-common: &common
  network: host
  deploy:
    <<: *deploy-base
  networks:
    hostnet: {}

networks:
  hostnet:
    external: true
    name: host

volumes:
  node-red_data:

services:
  node-red:
    <<: *common
    image: yangm97/trash:openvpn
    deploy:
      <<: *deploy-base
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
    volumes:
      - node-red_data:/data
```

**Comment by muayyad-alsadi** [comment]
I've replaced image with to make it run "busybox httpd -f"

https://paste.fedoraproject.org/paste/W8vlAvwNNzEuvTlWh2AH7w

it's basically just (with yaml syntax surag)

```
---
version: '3.6'
networks:
  hostnet:
    external: true
    name: host
volumes:
  node-red_data: 
services:
  node-red:
    network: host
    deploy:
      restart_policy:
        delay: 2s
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
    networks:
      hostnet: {}
    image: busybox
    command: busybox httpd -h /data -f -p 8080
    volumes:
    - node-red_data:/data
```
