### ISSUE TITLE
[feature request] consider a pod mapping based on network (names)

### ISSUE THREAD

**Issue by aanno** [containers/podman-compose#363]
**Is your feature request related to a problem? Please describe.**

There is no current [pod mapping](https://github.com/containers/podman-compose/blob/devel/docs/Mappings.md) that takes (named) network into account. However, most more complex `docker-compose` yml files, separate/restrict container network interaction based on (named) nextworks.

For example, consider nextcloud running on a DB behind a proxy:

Simplified pseudo yml:
```yml
version: '3.7'

services:
  db:
    image: mariadb
    networks:
      - db-tier
  app:
    image: nextcloud:fpm-alpine
    depends_on:
      - db
    networks:
      - proxy-tier
      - db-tier
  web:
    image: nginx:alpine
    ports:
      - ${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}
      - ${SERVER_HTTPS_PORT}:${SERVER_HTTPS_PORT}
    depends_on:
      - app
    networks:
      - proxy-tier

networks:
    proxy-tier:
        external: true
        name: proxy-tier
    db-tier:
        external: true
        name: db-tier
```

**Describe the solution you'd like**

I think it should be possible to support such a setup with a new _pod mapping_ that honours (named) networks. If there would only be _one_ external network, a similar result could be attained with something like:

```sh
podman-compose -t identity --podman-run-args='--pod nc --net proxy-tier' -p nc up -d
```

However, this solution does not work with more than one network defined.
