### ISSUE TITLE
Cannot configure network in docker-compose.yml and assign static IP address

### ISSUE THREAD

**Issue by andneuma** [containers/podman-compose#399]
**Describe the bug**
I can create a network with a proper subnet configuration in podman like so: `podman network create foo --subnet=10.12.1.0/24`.

Since I want to startup multiple services at once, assign them to the same network AND assign a static IP address to each service I tried the following in a `docker-compose.yml`:

```
version: '2'
  
services:
  nginx:
    image: nginx:alpine
    networks:
      foo:
        ipv4_address: 192.168.55.10

networks:
  foo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.12.1.0/24
```

When I inspect the newly created network I discovered, that it has been prefixed (results in `svd_foo`) and that the network configuration has not been applied - the subnet scheme is some random default:

```
    ...
        "cniVersion": "0.4.0",
        "name": "svd_foo",
        "plugins": [
            {
                "bridge": "cni-podman1",
                "hairpinMode": true,    ...
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.89.0.1",
                                "subnet": "10.89.0.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
    ...
```

Inspecting the container reveals a proper association with the network but finally I want to be able to **assign fix ip addresses** so i have to predefine network structure and service addresses. Both did not work like it did using docker-compose

```
"Networks": {
                "svd_foo": {
                    "EndpointID": "",
                    "Gateway": "10.89.0.1",
                    "IPAddress": "10.89.0.6",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "5e:9c:4b:42:00:2f",
                    "NetworkID": "svd_foo",
                    "DriverOpts": null,
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "nginx"
                    ]
                }
            }
```

**To Reproduce**
1. With the above `docker-compose.yml` startup container with `podman-compose up -d`
2. `podman inspect foo` reveals network configuration
3. `podman inspect <CONTAINER_ID>` reveals container network associations

**Expected behavior**
Expecting `podman-compose` to create a network with custom subnet configuration as defined in `docker-compose.yml` and assign container a fix IPv4 inside that network

**Actual behavior**
When I inspect the container I can see the assignment to the proper network but the newly created network settings have not been applied (e.g. subnet is something else). Also I could not assign a fix ipv4 address.

```
$ podman-compose version
using podman version: 3.4.2
podman version 3.4.2
```

**Environment:**
 - OS: Ubuntu 20.04
 - podman version: 3.4.2
 - podman compose version: 3.4.2

**Comment by linsijia1002** [comment]
The same thing happened to me

**Comment by muayyad-alsadi** [comment]
you should not rely on specific IP for containers
containers are not pets, you should not care about their IP being fixed.
containers are disposable.

if you want to to expose to address container you either

- expose the container port to some host port, the use that port
- use network_mode=host, then address the host

[read more about this on 12 factor](https://12factor.net/port-binding)

regardless of this I've fixed this, please test the above commit or latest devel branch

please note that the ip should belong to the network

```yaml
version: '3'
services:
  web:
    image: busybox
    command: httpd -f -p 8123 -h /etc/
    networks:
      foo:
        ipv4_address: 10.12.1.10

networks:
  foo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.12.1.0/24
```

verified with

```
podman-compose up -d
podman-compose exec web ifconfig
```
