### ISSUE TITLE
support `network_mode: "service:my_srv"`

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman-compose#407]
**Is your feature request related to a problem? Please describe.**

* sometimes we want to containers to talk to each other using localhost
* this is part of compose spec

**Additional context**
it's missed after #379 

```yaml
version: '3'
services:
  web:
    image: busybox
    command: ["httpd", "-f", "-p", "8080", "-h", "/etc"]
  web2:
    image: busybox
    command: ["httpd", "-f", "-p", "8000", "-h", "/etc"]
    network_mode: "service:web"

```
