### ISSUE TITLE
Support slirp4netns

### ISSUE THREAD

**Issue by p-fruck** [containers/podman-compose#415]
**Is your feature request related to a problem? Please describe.**
I would like to define `slirp4netns` as a networkdriver, so podman is able to resolve source IPs.

**Describe the solution you'd like**
`docker-compose` is able to handle the following specification and configure slirp4netns for a given service:

```yaml
services:
  example:
    network_mode: "slirp4netns:port_handler=slirp4netns"
    environment:
      - NETWORK_INTERFACE=tap0
    ...
```

However, podman-compose fails to create a network with the given mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
