### ISSUE TITLE
Memory restriction

### ISSUE THREAD

**Issue by jainamtrivedi-crest** [containers/podman-compose#417]
I want to restrict new in rabbitmq service. I am using `podman-compose up -d` command to start all the services.
![image](https://user-images.githubusercontent.com/77317274/152160703-57672b53-8095-447c-9056-d69ce2376fd2.png)
I want to limit rabbitmq container's memory to 2GB but after running above command I am not able to see restricted memory of rabbitmq container. It shows 4GB memory in `podman stats` command's output.

I am not seeing --memory in podman run command too. Here is the output of few commands.

- Few part of `podman-compose up -d` command:

![image](https://user-images.githubusercontent.com/77317274/152161281-09c719b3-c443-43cc-9e84-468e3ada53c3.png)

- output of `podman stats` command:

![image](https://user-images.githubusercontent.com/77317274/152161324-8e575b8b-7ffd-45f9-9af9-b083829c469a.png)

Am I doing something wrong?

**Comment by jainamtrivedi-crest** [comment]
I am using 3.3 version, so `mem_limit: 2g` won't work

**Comment by jainamtrivedi-crest** [comment]
If I use the command to run only rabbitmq service with `--memory=2G` flag added, I can see restricted memory usage under `podman stats` command. 
![image](https://user-images.githubusercontent.com/77317274/152204587-6a7d65c0-fefd-4353-af0a-103d01476856.png)
but I don't want to do this.

**Comment by muayyad-alsadi** [comment]
> I am using 3.3 version, so mem_limit: 2g won't work

podman-compose is a superset of all docker-compose version, even if it's 3.3 it will work.

**Comment by jainamtrivedi-crest** [comment]
I am using podman version 3.3.1 and podman-compose version 0.1.7. That might be the issue? because I am not able to find container_to_res_args() method in podman_compose.py file.
I have installed podman-compose using `yum install podman-compose` command and I have RHEL 8 os.

**Comment by muayyad-alsadi** [comment]
please upgrade podman-compose to the latest pip version. if you know the maintainer please ask the maintainer to upgrade it.

**Comment by jainamtrivedi-crest** [comment]
Yes, I have upgraded podman-compose version to the latest version. And now I am able to see all the options getting applied to the container like memory limit, logs limit etc.

But found another issue; with the older version of podman-compose all the containers were up and running but now with the latest version UI service is existing and it is showing `nx: [emerg] host not found in upstream "core" in /etc/nginx/conf.d/nginx.conf:19` error. There is a `links` option in UI service which is set to `Core` service.

I diffed podman run command (echoed when we hit podman-compose up -d) of the older version with the latest version and found that newer version is missing `--add-host` option.

- older version of podman-compose 
`podman run --name=tacloudexchange_ui_1 -d --pod=tacloudexchange --label com.centurylinklabs.watchtower.enable=true --label io.podman.compose.config-hash=123 --label io.podman.compose.project=tacloudexchange --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=ui -e CE_API_URL=http://core/ -v /root/ta_cloud_exchange/./data/ssl_certs:/tmp/ssl_certs:z --add-host rabbitmq-stats:127.0.0.1 --add-host tacloudexchange_rabbitmq-stats_1:127.0.0.1 --add-host mongodb-primary:127.0.0.1 --add-host tacloudexchange_mongodb-primary_1:127.0.0.1 --add-host core:127.0.0.1 --add-host tacloudexchange_core_1:127.0.0.1 --add-host ui:127.0.0.1 --add-host tacloudexchange_ui_1:127.0.0.1 --add-host watchtower:127.0.0.1 --add-host tacloudexchange_watchtower_1:127.0.0.1 --restart on-failure:5 [index.docker.io/netskopetechnicalalliances/cloudexchange:ui3-latest](http://index.docker.io/netskopetechnicalalliances/cloudexchange:ui3-latest`

- Latest version of podman-compose
`podman run --name=ta_cloud_exchange_ui_1 -d --label com.centurylinklabs.watchtower.enable=true --label io.podman.compose.config-hash=123 --label io.podman.compose.project=ta_cloud_exchange --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=ta_cloud_exchange --label com.docker.compose.project.working_dir=/root/ta_cloud_exchange --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=ui -e CE_API_URL=http://core/ -v /root/ta_cloud_exchange/data/ssl_certs:/tmp/ssl_certs:z --net ta_cloud_exchange_default --network-alias ui --log-driver=k8s-file --log-opt=max-size=10m --log-opt=max-file=5 -p 80:3000 --restart on-failure:5 [index.docker.io/netskopetechnicalalliances/cloudexchange:ui3-latest](http://index.docker.io/netskopetechnicalalliances/cloudexchange:ui3-latest`

**Comment by muayyad-alsadi** [comment]
`--add-host ui` is replaced with  `--network-alias ui`

most likely you don't have a podman dnsmasq plugin installed
please read the readm.md you will find the name of that package

**Comment by jainamtrivedi-crest** [comment]
Yes, I did not have dnsmasq plugin installed. I installed it but still having same error. 

- UI Service: 
![image](https://user-images.githubusercontent.com/77317274/152315795-00506aa6-cad8-4440-b525-fd55ce9675dd.png)

**Comment by muayyad-alsadi** [comment]
you need to recreate the containers, `podman-compose down`

**Comment by jainamtrivedi-crest** [comment]
I already did that  but no luck. Not sure what is missing here as older version of podman-compose was running fine and getting this error after upgrading to latest.

**Comment by muayyad-alsadi** [comment]
can you try a simple minimal stack with two "busybox httpd -f" services, and check if they are resolvable and reachable from each other like this

https://github.com/containers/podman-compose/tree/devel/tests/nets_test1

**Comment by jainamtrivedi-crest** [comment]
they are reachable. Used same docker-compose.yml file you have used in mentioned link.

**Comment by muayyad-alsadi** [comment]
so what makes your case not reachable/resolvable? what is the difference between how your yaml and mine?

**Comment by jainamtrivedi-crest** [comment]
I am using this yml file: 
```
version: "3.3"
services:
  rabbitmq-stats:
    image: index.docker.io/bitnami/rabbitmq:3.8
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1
    restart: on-failure:5
    volumes:
      - ./data/rabbitmq/custom.conf:/bitnami/rabbitmq/conf/custom.conf:z
    ports:
      - '15672:15672'
      - '5672:5672'
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G
  mongodb-primary:
    image: index.docker.io/bitnami/mongodb:4.4
    volumes:
      - ./data/mongo-data:/bitnami/mongodb:z
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=cte
    restart: on-failure:5
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: "10m"
        max-file: "5"
  core:
    image: index.docker.io/${CORE_TAG}
    volumes:
      - ./data/custom_plugins:/opt/netskope/plugins/custom_plugins:z
    environment:
      - MONGO_CONNECTION_STRING=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-primary:27017/cte
      - RABBITMQ_CONNECTION_STRING=amqp://user:bitnami@rabbitmq-stats
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - ENABLE_CELERY_BEAT=true
      #- DOCKER_USERNAME=${DOCKER_USERNAME}
      #- DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - ANALYTICS_BASE_URL=https://reporting.netskope.tech
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
      - MAX_MAINTENANCE_WINDOW_MINUTES=${MAX_MAINTENANCE_WINDOW_MINUTES}
      - PULL_THREADS=${PULL_THREADS}
      - MAX_WAIT_ON_LOCK_IN_MINUTES=${MAX_WAIT_ON_LOCK_IN_MINUTES}
    restart: on-failure:5
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    labels:
      - com.centurylinklabs.watchtower.enable=true
  ui:
    image: index.docker.io/${UI_TAG}
    restart: on-failure:5
    environment:
      - CE_API_URL=http://core
    volumes:
      - ./data/ssl_certs:/tmp/ssl_certs:z
    ports:
      - ${UI_PORT}:3000
    links:
      - core
    labels:
      - com.centurylinklabs.watchtower.enable=true
    logging:
      options:
        max-size: "10m"
        max-file: "5"
  watchtower:
    image: index.docker.io/containrrr/watchtower:1.3.0
    volumes:
      # - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - WATCHTOWER_LABEL_ENABLE=true
    restart: on-failure:5
    ports:
      - 8080:8080
    command: --http-api-update
    logging:
      options:
        max-size: "10m"
        max-file: "5"
```
which is running smoothly in docker but throwing errors while running it in podman. Not sure what to do to make it compatible with podman
