### ISSUE TITLE
Missing support for DNS option

### ISSUE THREAD

**Issue by CayoM** [containers/podman-compose#431]
**Describe the bug**
While using docker-compose it was possible to define a DNS-Server to be used as in the example below:

```
version: '3.1'
services:
    haproxy:
        image: haproxytech/haproxy-debian:2.0
        container_name: haproxy
        restart: always
        dns:
            - 172.16.16.3
        ports:
            - '6443:6443'
            - '22623:22623'
            - '443:443'
            - '80:80'
        volumes:
            - './config:/usr/local/etc/haproxy'
        network_mode: "host"
```

However, when using podman-compose to start the same docker-compose file, the "--dns" option is just ignored. This can be seen in the following output:

```
podman-compose up -d
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
['podman', 'network', 'exists', 'haproxy_default']
podman run --name=haproxy -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=haproxy --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=haproxy --label com.docker.compose.project.working_dir=/opt/haproxy --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=haproxy --network host -v /opt/haproxy/config:/usr/local/etc/haproxy --net haproxy_default --network-alias haproxy -p 6443:6443 -p 22623:22623 -p 443:443 -p 80:80 --restart always haproxytech/haproxy-debian:2.0
```

As a result, HAProxy is not working, since it can't resolve any of the defined servers.

**To Reproduce**
to reproduce this behavior, you can set a "dns: 1.2.3.4" in a docker-compose file and spin it up with podman-compose.

**Expected behavior**
I would expect podman-compose support the same options as docker-compose regarding dns.

**Actual behavior**
I could not find anything related to the dns option in the podman-compose code.

**Environment:**
 - OS: Linux Ubuntu 20.04
 - podman version: 3.4.2
