### ISSUE TITLE
network_mode issue?

### ISSUE THREAD

**Issue by Shkrelic** [containers/podman-compose#451]
### network_mode: "host" is not working?

I'm not certain if I am just making a mistake or if there's something wrong, but I cannot get podman-compose to pass --network host in my docker-compose.yml. I have tried using all of the following:
`network_mode: "host"`
`network_mode: host`
`network: host`
`network: "host"`

### Environment

Red Hat Enterprise Linux release 8.5 (Ootpa) 4.18.0-348.20.1.el8_5.x86_64
using podman version: 3.4.2
podman-composer version  1.0.3
podman version 3.4.2

### Steps to reproduce
Here's my docker-compose.yml
```
---
version: "2.1"
services:
  plex:
    image: plexinc/pms-docker:latest
    network_mode: "host"
    container_name: plex
    environment:
      - PLEX_CLAIM=**REDACTED**
    volumes:
      - /opt/plex/config:/config:z
      - /opt/plex/transcode:/transcode:z
      - /nas01/data/media/tv:/tv
      - /nas01/data/media/movies:/movies
      - /nas01/data/media/music:/music
    restart: unless-stopped
    ports:
     - "32400:32400/tcp"
```

Here's the output when I run podman-compose up -d

```
podman-compose up -d
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
['podman', 'network', 'exists', 'plex_default']
podman run --name=plex -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=plex --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=plex --label com.docker.compose.project.working_dir=/opt/plex --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=plex --network host -e PLEX_CLAIM=claim-REDACTED -v /opt/plex/config:/config:z -v /opt/plex/transcode:/transcode:z -v /nas01/data/media/tv:/tv -v /nas01/data/media/movies:/movies -v /nas01/data/media/music:/music --net plex_default --network-alias plex -p 32400:32400/tcp --restart unless-stopped plexinc/pms-docker:latest
```

### Expected behavior
podman should set network to host.

### Actual behavior
podman sets network to bridge.

here's the output of podman inspect on that container:
```            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "1900/udp": null,
                "32400/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "32400"
                    }
                ],
```

**Comment by muayyad-alsadi** [comment]
I've tried the latest devel branch on [this test](https://github.com/containers/podman-compose/blob/devel/tests/nethost/docker-compose.yaml)

```yaml
version: '3'
services:
  web:
    image: busybox
    command: httpd -f -p 8123 -h /etc/
    network_mode: host
```

and it worked fine it run something like

```
podman create ###### --network host busybox httpd -f -p 8123 -h /etc/
```

and the port is actually opened

```
$ curl localhost:8123/hosts
```

please try latest devel branch and tell me if it works for you
