### ISSUE TITLE
Trying to specify network: RuntimeError: missing networks: default

### ISSUE THREAD

**Issue by Reizake** [containers/podman-compose#452]
Hello,
I have been trying to set up a nextcloud with mariadb:
```
services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - podman
    environment:
      - MYSQL_ROOT_PASSWORD= xxxx
      - MYSQL_PASSWORD= xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/gp-theme
    networks:
      - podman
    environment:
      - MYSQL_PASSWORD= xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```

but everytime I try to get it on a network this occurs:

```
['podman', '--version', '']
using podman version: 3.2.1
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: default
```

Is there something I am missing when it comes to setting up networks? if I don't include the network it always puts them in a "nextcloud_default" network.

**Comment by muayyad-alsadi** [comment]
please note that spaces are part of YAML syntax, you can't omit them.

please edit your issue to put three back ticks 

```
this -> ```
```

before and after the code

**Comment by muayyad-alsadi** [comment]
https://github.com/compose-spec/compose-spec/blob/master/spec.md#networks-top-level-element

your yaml should have top level networks with the name of your network, like this

```yaml
---
networks:
  podman:
services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - podman
    environment:
      - MYSQL_ROOT_PASSWORD= xxxx
      - MYSQL_PASSWORD= xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/gp-theme
    networks:
      - podman
    environment:
      - MYSQL_PASSWORD= xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```
