### ISSUE TITLE
Podman-compose is not handling networks: RuntimeError: missing networks:

### ISSUE THREAD

**Issue by Reizake** [containers/podman-compose#463]
When trying to make a static IP setting based specifically on this documentation under the "ipv4_address, ipv6_address" section:
https://docs.docker.com/compose/compose-file/compose-file-v3/

I am receiving the "RuntimeError: missing networks: default,podman" error. I have tried a variety of other methods to no avail. it seems that podman-compose is not properly reading the networks: section in the yaml

here is my compose file:

```
version: '3'

networks:
  default:
    external:
      name: podman
  podman:
    ipam:
      driver: default
      config:
        - subnet: "10.88.2.0/24"


services:

  app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html 
    environment:
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
      - MYSQL_HOST=xxxx
    networks:
      podman:
           ipv4_address:10.88.2.10

  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
    networks:
     podman:
          ipv4_address:10.88.2.11
```

And here are the results I get:

```
User@Computer:/DAS/PodmanVolumes/nextcloud$ sudo podman-compose  up -d
['podman', '--version', '']
using podman version: 3.2.1
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: default,podman
```

I have tried using default as well as "network_mode" neither gave good results.
please let me know if there is any other info needed or things you would like me to try.

**Comment by muayyad-alsadi** [comment]
## Question?

what version of podman-compose are you using?

## NOTE

the `external` part in networks mean you need to manage it yourself, you should create this network, see [compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#external)


here is an example how to specify static ip

```yaml
version: "3"
networks:
  app1_container_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
services:
  app1:
    image: busybox
    command: httpd -f -p 8080 -h /etc/
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.11
```

## NOTE 2
specifying address is against the 12 factor you should use [port mapping](https://12factor.net/port-binding) not ip address mapping.

**Comment by Reizake** [comment]
I am running:

```
['podman', '--version', '']
using podman version: 3.2.1
podman-composer version  1.0.3
podman --version 
podman version 3.2.1
exit code: 0
```


just to confirm. this will still put it in the pre-existing network "podman" correct?

Either way when I set my compose file as such:
```
version: '3'

networks:
  podman:
    ipam:
      driver: default
      config:
        - subnet: "10.88.2.0/24"


services:

  app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html 
    environment:
      - MYSQL_PASSWORD=xxxx
      - MYSQL_USER=xxxx
      - MYSQL_HOST=xxxx
    networks:
       podman:
           ipv4_address:10.88.2.10

  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
    networks:
       podman:
          ipv4_address:10.88.2.11

```

it still spits this error:

```
user@computer:/DAS/PodmanVolumes/nextcloud$ sudo podman-compose  up -d
['podman', '--version', '']
using podman version: 3.2.1
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: podman
```

**Comment by muayyad-alsadi** [comment]
would you please try latest branch.

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

I've tested it with equivalent yaml and it worked 

```yaml
---
version: "3"
networks:
  podman:
    ipam:
      driver: default
      config:
        - subnet: "10.88.2.0/24"
services:
  web1:
    image: busybox
    command: httpd -f -p 8080 -h /etc/
    networks:
      podman:
        ipv4_address: 10.88.2.10
  web2:
    image: busybox
    command: httpd -f -p 8080 -h /etc/
    networks:
      podman:
        ipv4_address: 10.88.2.11
```

**Comment by muayyad-alsadi** [comment]
> , but is there a command to stop that from happening in the compose file. or just a general way of setting pod configuration?

to prevent creating a pod

```
  --no-pod              disable pod creation
```

to adjust pod params

```
  --pod-args pod_args   disable pod creation
```

there is no way to control that from inside the yaml

**Comment by jave** [comment]
Just a note that upgrading to podman-compose 1.0.4 fixed the same problem for me

**Comment by mchoeti** [comment]
> there is no way to control that from inside the yaml
Hm... but doing this
`podman-compose up --no-pod`

results in 
`unrecognized arguments: --no-pod`

Do you have an example?

**Comment by midu16** [comment]
@muayyad-alsadi is there any plan on the podman-compose 1.0.4 rpm release? Fedora 37 is still using the 1.0.3.

**Comment by x1ntt** [comment]
Try changing `networks` to `nets`

**Comment by Antoniossss** [comment]
Having the exact same issue as @mreiche here. Any ideas??

**Comment by mreiche** [comment]
> Having the exact same issue as @mreiche here. Any ideas??

I use `podman` network instead.

**Comment by mreiche** [comment]
I came back to this, because my problem seems to be related to Podman 3.4.4 on Ubuntu 22.04, because there is no official newer version available and I need to get this fixed. So this is my workarround.

When I created an external network, I saw a list with different versions.
```shell
podman network ls
NETWORK ID    NAME        VERSION     PLUGINS
2f259bab93aa  podman      0.4.0       bridge,portmap,firewall,tuning
8ac92e008a0e  my_network  1.0.0       bridge,portmap,firewall,tuning,dnsname
```
and a suspicious message:
´´´
WARN[0000] Error validating CNI config file /etc/cni/net.d/my_network.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"]
```
So I edited `/etc/cni/net.d/my_network.conflist` and changed the version to `0.4.0`.
```shell
podman network ls
NETWORK ID    NAME        VERSION     PLUGINS
2f259bab93aa  podman      0.4.0       bridge,portmap,firewall,tuning
8ac92e008a0e  my_network  0.4.0       bridge,portmap,firewall,tuning,dnsname
```
This network I could use with `podman-compose` like:
```yaml
networks:
  default:
    name: my_network
    external: true
´´´
where also DNS resolution works now.

**Comment by Antoniossss** [comment]
Is that a fix or a way to mute version  compatibility  warnings?

sob., 27 sty 2024, 20:09 użytkownik Mike Reiche ***@***.***>
napisał:

**Comment by mreiche** [comment]
It's a workaround.

**Comment by Zocker1999NET** [comment]
I have the same issue on:
- Debian GNU/Linux bookworm, arm64, podman 4.3.1 (from Debian)
- tried on both user accounts with multiple podman-compose versions
	- `1.0.3-3` from Debian
	- `1.0.6-1~bpo12+1` from Debian
	- `1.0.7` from https://github.com/containers/podman-compose/archive/devel.tar.gz

Weirdly, I only have this issue on the user account I specifically created for podman. On my user account on the same system, the same compose file just works. I nuked `~/.config/cni` & `.local/share/containers` on both accounts at the start and checked before each test that the previous containers & networks were no longer listed by podman.
I also tried putting the podman account into the same groups as mine, without success. AFAIK those accounts have only a few differences where I could remotely imagine that those may could cause this issue.

<details>
<summary>Table of Differences</summary>

Account Name | `zocker` | `podman`
--- | --- | ---
Home | `/home/zocker` | `/var/lib/podman-env`
UID | 1000 | 995
Primary GID | 1000 | 994
`/etc/subuid` & `/etc/subgid` entries | `zocker:100000:65536` | `podman:165536:65536`

</details>

I tested that with this simple compose file:
```yaml
version: "2"

services:
  test:
    image: hello-world
```
