### ISSUE TITLE
Port mapping not works under multiple networks assigned for a container

### ISSUE THREAD

**Issue by SadPencil** [containers/podman-compose#484]
**Describe the bug**

When a container is assigned with more than one network, the port mapping does not work.

**To Reproduce**

`docker-compose.yml` file:
```yaml
networks:
  test-net-1:
  test-net-2: # comment out this line to test the difference

services:
  node1:
    image: python
    ports:
      - "8000:8000"
    command: python3 -m http.server 8000
    networks:
      - test-net-1
      - test-net-2 # comment out this line to test the difference
```

Then, type `podman-compose up` to start the container. The port 8000 is not accessible outside the sever (timed-out).
Comment out two `test-net-2` lines, and then the port is accessible.

**Expected behavior**
The port mapping works under multiple network assignment.

**Actual behavior**
The port mapping does not work (timed-out) under multiple network assignment.

**Output**

```
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.2
podman-composer version 1.0.4
podman --version 
podman version 4.0.2
exit code: 0
```

```
$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.2
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=podman-test', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_podman-test --infra=false --share=
ba6a4319913e685962375598bbad749b3d56f44f9a9e648154a03da3fcc8559f
exit code: 0
['podman', 'network', 'exists', 'podman-test_test-net-1']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=podman-test', '--label', 'com.docker.compose.project=podman-test', 'podman-test_test-net-1']
['podman', 'network', 'exists', 'podman-test_test-net-1']
['podman', 'network', 'exists', 'podman-test_test-net-2']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=podman-test', '--label', 'com.docker.compose.project=podman-test', 'podman-test_test-net-2']
['podman', 'network', 'exists', 'podman-test_test-net-2']
podman create --name=podman-test_node1_1 --pod=pod_podman-test --label io.podman.compose.config-hash=b47f558ff13b1ff6949e16ae63838f3add49d46bf7c9301c9fe4915e1159ba6d --label io.podman.compose.project=podman-test --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=podman-test --label com.docker.compose.project.working_dir=/tmp/podman-test --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=node1 --net podman-test_test-net-2,podman-test_test-net-1 --network-alias node1 -p 8000:8000 python python3 -m http.server 8000
a750310eef786b62df03274ec4fd567f7fc7b83f1e7adafca9dfb78e2b88dae5
exit code: 0
podman start -a podman-test_node1_1
```

**Environment:**
 - OS: CentOS 8 Stream
 - podman version: 4.0.2
 - podman compose version: f42b568fc257f4577d33d05e271d827788612d64

**Additional context**

firewalld v0.9.3

**Comment by muayyad-alsadi** [comment]
could this be a bug in `podman`?
they have been working on multiple networks and they have reworked it in 4.x

**Comment by mokibit** [comment]
Closing this issue as it no longer reproduces with current versions of `podman` and `podman-compose`.

I tested the exact scenario described in the bug report with the following minimal setup. Port mapping works correctly when the container is attached to multiple networks:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`docker-compose.yml` file:
```
networks:
  test-net-1:
  test-net-2:

services:
  node1:
    image: python
    ports:
      - "8000:8000"
    command: python3 -m http.server 8000
    networks:
      - test-net-1
      - test-net-2
```
Running these commands creates the container successfully, and the ports are displayed correctly:
```
$ podman-compose up -d
...
$ podman ps -a
2a751a606137  docker.io/library/python:latest                                    python3 -m http.s...  About a minute ago  Up About a minute  0.0.0.0:8000->8000/tcp     test-podman-compose_node1_1
```
```
$ curl -s http://localhost:8000/
```
 The connection succeeds and returns the Python HTTP server directory listing, confirming the port mapping works correctly with multiple networks assigned. This was likely a bug in older versions and has since been resolved. If anyone can still reproduce this with current versions of `podman` and `podman-compose`, please comment below and we can reopen the issue.
