### ISSUE TITLE
Any way to build from git like in normal docker-compose?

### ISSUE THREAD

**Issue by zabihexes** [containers/podman-compose#506]
https://docs.docker.com/engine/reference/commandline/build/#git-repositories

Example yaml.
```yaml
services:
    test:
        build:
            context: https://github/user/repository.git#prod
            dockerfile: Dockerfile
        container_name: test
        restart: unless-stopped
```
This would build the image from the specified repository from branch prod.

Thanks

**Comment by dploeger** [comment]
Yes, this doesn't work with 1.2.0 yet apparently.

**Comment by mokibit** [comment]
Closing this issue as the feature is already supported, was fixed by https://github.com/containers/podman-compose/pull/1171.
Now `podman-compose` correctly passes git repository URLs as build contexts to `podman build`, which natively handles cloning git repositories (including branch references).

Minimal reproduction, environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file:
```
services:
  test:
    build:
      context: https://github.com/alpinelinux/docker-alpine.git#master
      dockerfile: Dockerfile
```
Build from the git repository:
```
$ podman-compose build
```
Or build and start directly:
```
$ podman-compose up -d
<...>
$ podman ps -a
CONTAINER ID  IMAGE                                                              COMMAND               CREATED        STATUS                    PORTS                      NAMES
5769372f0856  localhost/test-podman-compose_test:latest                          /bin/sh               3 seconds ago  Exited (0) 3 seconds ago                             test-podman-compose_test_1
```
- `podman-compose build` successfully passes the git URL to `podman build`.
- `podman-compose up -d` successfully builds from the git repository and starts the container.
- Git URLs with branch references (e.g., `https://github.com/.../repo.git#master`) are also handled correctly.
