### ISSUE TITLE
Container `networks` should fall back to list handling when no value is provided for network key

### ISSUE THREAD

**Issue by mkykadir** [containers/podman-compose#516]
**Is your feature request related to a problem? Please describe.**
Some can configure a container within compose file with following `networks` field;
```
    image: geth-node:local
    volumes:
      - ./nodes/bootnode:/bootnode
    networks:
      priv-eth-net:
```
this configuration (network key without any value) doesn't fail under `docker-compose` but throws exception under `podman-compose` [here](https://github.com/containers/podman-compose/blob/4a73ae86bc0b4a84461f07a391c2eab8893cee33/podman_compose.py#L778). Changing configuration to;
```
    networks:
        - priv-eth-net
```
resolves the problem but I think this should be handled silently, or exception message should be more clear.

**Describe the solution you'd like**
Handle the dictionary without value silently and fallback to list implementation.

**Describe alternatives you've considered**
Clear exception message
