### ISSUE TITLE
Run command works from podman cmd but not as docker-compose file

### ISSUE THREAD

**Issue by supermar1010** [containers/podman-compose#52]
Hi,
another problem from my side.
I have a docker-compose file which looks like this:

```
version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:Z
    ports:
      - '3000:3000'
    command: bash -c "npm install && node index.js"
```
The command that you see at the end works when invoking podman like this: `podman run -it --rm -p 3000:3000 --name NodeTest -v "$PWD":/home/node/app:Z -w /home/node/app node:latest bash -c "npm install && node index.js"` which should be equivalent to what my docker-compose does.
When I run the command everything works as expected(apart from not being able to kill it...)
But when I run `podman-compose up`, this happens: 
```
podman start -a NodeTest_node_1
install: -c: line 0: unexpected EOF while looking for matching `"'
install: -c: line 1: syntax error: unexpected end of file
1
```

Do you have any idea what could be causing this?

With best regards
Mario
