### ISSUE TITLE
Project name argument does not corespond to docker compose specification

### ISSUE THREAD

**Issue by c0m1c5an5** [containers/podman-compose#533]
**Describe the bug**
By docker compose specification [project name has to be prepended to container name](https://docs.docker.com/compose/reference/envvars/#compose_project_name). podman-compose does not adhere to this rule and just creates a container without prepending a project name. Personally I find it quite inconvenient.

![screenshot](https://user-images.githubusercontent.com/30040354/181361091-88029c8f-1a3b-47b5-8d7c-04796001ef01.png)

**To Reproduce**
1. what is the content of the current working directory (ex. `docker-compose.yml`, `.env`, `Dockerfile`, ...etc.)
```
# compose.yml
version: '3'
volumes:
  postgres_data:
    driver: 'local'
services:
  postgres:
    image: 'postgres:9.6'
    container_name: 'postgres'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
```
2. Run podman-compose up -d
3. Run podman ps

**Expected behavior**
Project name gets prepended to container name.
```
[user@pc project]$ podman-compose up -d
['podman', '--version', '']
using podman version: 4.1.1
** excluding:  set()
podman volume inspect project_postgres_data || podman volume create project_postgres_data
['podman', 'volume', 'inspect', 'project_postgres_data']
['podman', 'network', 'exists', 'project_default']
podman run --name=project-postgres -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=project --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=project --label com.docker.compose.project.working_dir=.../project --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=postgres -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -v project_postgres_data:/var/lib/postgresql/data --net project_default --network-alias postgres postgres:9.6
98ce2b67147518e8f5312e00ac1235847486321500c78a92d30a6a664a0e52f8
exit code: 0
[user@pc project]$ podman ps
CONTAINER ID    IMAGE                           COMMAND      CREATED         STATUS             NAMES
98ce2b671475    docker.io/library/postgres:9.6  postgres     22 seconds ago  Up 22 seconds ago  project-postgres
```

**Actual behavior**
Project name does not get prepended to container name (tested with both -p option and without one).
```
[user@pc project]$ podman-compose up -d
['podman', '--version', '']
using podman version: 4.1.1
** excluding:  set()
podman volume inspect project_postgres_data || podman volume create project_postgres_data
['podman', 'volume', 'inspect', 'project_postgres_data']
['podman', 'network', 'exists', 'project_default']
podman run --name=postgres -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=project --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=project --label com.docker.compose.project.working_dir=.../project --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=postgres -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -v project_postgres_data:/var/lib/postgresql/data --net project_default --network-alias postgres postgres:9.6
98ce2b67147518e8f5312e00ac1235847486321500c78a92d30a6a664a0e52f8
exit code: 0
[user@pc project]$ podman ps
CONTAINER ID    IMAGE                           COMMAND      CREATED         STATUS             NAMES
98ce2b671475    docker.io/library/postgres:9.6  postgres     22 seconds ago  Up 22 seconds ago  postgres
```

**Podman-compose Version**
```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.1.1
podman-composer version  1.0.3
podman --version 
podman version 4.1.1
exit code: 0
```

**Environment:**
 - OS: Linux pc.aln 5.18.13-200.fc36.x86_64 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 GNU/Linux
 - podman version:  4.1.1
 - podman compose version: 1.0.3

**Comment by muayyad-alsadi** [comment]
container name defaults to project name plus *service* name unless you overrided the default with container_name

here is a small example

```yaml
---
version: '3'
services:
  web:
    image: busybox
    container_name: myweb
    command: httpd -f -p 8080 -h /etc
```

here is the docker compose behavior in a directory called myproj

```
$ docker-compose up -d
Creating network "myproj_default" with the default driver
Creating myweb ... done
$ docker ps | grep myproj || echo "not found"
not found
$ docker ps | grep myweb
5870b268503a   busybox                 "httpd -f -p 8080 -h…"   23 seconds ago   Up 21 seconds   myweb
```

as you can see myproj was not added.

if you want it to be added remove `container_name` to leave the default behavior as is

```
---
# compose.yml
version: '3'
volumes:
  postgres_data:
    driver: 'local'
services:
  postgres:
    image: 'postgres:9.6'
    # container_name: 'postgres' # <-------------- remove this line
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
```
