### ISSUE TITLE
Ulimits not used

### ISSUE THREAD

**Issue by supermar1010** [containers/podman-compose#54]
Hello,
its me with another problem.
I want to change the ulimits in my container.

My docker-compose file looks like this:
```
version: '3'
services:
  tor-relay:
    image: tor-relay-stretch
    restart: always
    ports:
      - '9001:9001'
    volumes:
      - ./tor-data/:/root/.tor/:Z
      - ./torrc:/etc/tor/torrc:Z
    ulimits:
      nofile: 
        soft: 10000
        hard: 15000
```

When I start the container the `ulimit -n` still says 1024. The command line podman-compose prints looks like this ```podman run --name=TorMiddleRelay_tor-relay_1 -d --pod=TorMiddleRelay -l io.podman.compose.config-hash=123 -l io.podman.compose.project=TorMiddleRelay -l io.podman.compose.version=0.0.1 -l com.docker.compose.container-number=1 -l com.docker.compose.service=tor-relay --mount type=bind,source=/home/mario/podman/TorMiddleRelay/./tor-data/,destination=/root/.tor/,bind-propagation=Z --mount type=bind,source=/home/mario/podman/TorMiddleRelay/./torrc,destination=/etc/tor/torrc,bind-propagation=Z --add-host tor-relay:127.0.0.1 --add-host TorMiddleRelay_tor-relay_1:127.0.0.1 tor-relay-stretch```

This looks like it is not parsing the ulimit correctly, as it is not passing it to the podman commandline.
When I copy the commands compose executes and add the ulimit param manually it works. So it seems to be a problem podman-compose.
