### ISSUE TITLE
Error mount volume when /var/run/podman/podman.sock:/var/run/docker.sock

### ISSUE THREAD

**Issue by FourLeafTec** [containers/podman-compose#545]
**Describe the bug**
I use podman-compose to start a Coder container, this container need to connect linux socket.
Then I mount `/var/run/podman/podman.sock` to `/var/run/docker.sock` in compose.yaml.
When podman-compose up coder, then command change to `-v /run/podman/podman.sock:/var/run/docker.sock`.

**To Reproduce**
<details><summary>compose.yaml</summary>

<p>

```yaml
  version: 3.9
services:
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    container_name: coder
    ports:
      - "7080:7080"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      CODER_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:14
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - db_data:/var/lib/postgresql/data # Use "docker volume rm database_db_data" to reset Coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  coder_data:
  db_data:
    driver: local
```

</p>

</details>

**Output**

```
$ podman-compose version
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version 
podman version 3.4.4

$ podman-compose up
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
podman volume inspect pod_db_data || podman volume create pod_db_data
['podman', 'volume', 'inspect', 'pod_db_data']
['podman', 'network', 'exists', 'pod_default']
podman create --name=database --label io.podman.compose.config-hash=123 --label io.podman.compose.project=pod --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=pod --label com.docker.compose.project.working_dir=/home/ubuntu/pod --label com.docker.compose.project.config_files=compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=database -e POSTGRES_USER=username -e POSTGRES_PASSWORD=password -e POSTGRES_DB=coder -v pod_db_data:/var/lib/postgresql/data --net pod_default --network-alias database -p 5432:5432 --healthcheck-command /bin/sh -c 'pg_isready -U username -d coder' --healthcheck-interval 5s --healthcheck-timeout 5s --healthcheck-retries 5 postgres:14
dd689e9c08b13e2fc56fdb56f8bc88cab57c04cba487a0f9c58306045d265e3b
exit code: 0
['podman', 'network', 'exists', 'pod_default']
podman create --name=coder --label io.podman.compose.config-hash=123 --label io.podman.compose.project=pod --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=pod --label com.docker.compose.project.working_dir=/home/ubuntu/pod --label com.docker.compose.project.config_files=compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=coder -e CODER_PG_CONNECTION_URL=postgresql://username:password@database/coder?sslmode=disable -e CODER_ADDRESS=0.0.0.0:7080 -e CODER_ACCESS_URL={HOST} -v /run/podman/podman.sock:/var/run/docker.sock --net pod_default --network-alias coder -p 7080:7080 ghcr.io/coder/coder:latest
Error: statfs /run/podman/podman.sock: permission denied
exit code: 125
```

**Environment:**
 - OS: Linux
 - Arch: Arm64
