### ISSUE TITLE
.env ignores any keyval not beginning with "PODMAN_"

### ISSUE THREAD

**Issue by jamesob** [containers/podman-compose#559]
I have little idea why the original author wrote it this way, but podman-compose ignores any .env entry that is not prefixed with "PODMAN_". Docker-compose does not behave this way. Easy fix; [delete five lines of code](https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L1430-L1435).

**Comment by mokibit** [comment]
I can not reproduce this issue anymore.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file:
```
services:
  test:
    image: busybox
    environment:
      MY_VAR: ${MY_VAR1}
      MY_VAR2: ${MY_VAR2}
    command: ["sh", "-c", "echo MY_VAR1=$MY_VAR1 MY_VAR2=$MY_VAR2"]
```
.env file:
```
MY_VAR1=hello_from_env
MY_VAR2=42
```
The output of command `podman-compose config`:
```
services:
  test:
    command:
    - sh
    - -c
    - echo MY_VAR1=hello_from_env MY_VAR2=42
    environment:
      MY_VAR: hello_from_env
      MY_VAR2: '42'
    image: busybox
```
Both MY_VAR1 and MY_VAR2 (which do not start with PODMAN_) were correctly read from .env, interpolated into the compose file, and placed in the service environment, this issue can be closed as resolved.
