### ISSUE TITLE
RuntimeError: missing networks: podman

### ISSUE THREAD

**Issue by Reizake** [containers/podman-compose#584]
Hi Guys, I just updated from Ubuntu 20.11 to 21.11 and got everything running, but something has changed that is causing an issue with Podman-compose. when I run any of my config files. i.e.:

```
version: '3'

networks:
  podman:
    external:
       name: podman

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '192.168.1.100:80:80'
      - '192.168.1.100:81:81'
      - '192.168.1.100:443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
       podman:
         ipv4_address: 10.88.2.2
```

it now spits out this error:

```
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: podman
```

I'm not sure what to make of this. I spent a lot of time in the past getting the external network config working, and I haven't changed my yamls at ALL.

**Comment by praxis88** [comment]
I also ran into this today, podman version 4.2

**Comment by Vandaahl** [comment]
Same here. I'm on Fedora 35 (server edition) with Podman 3.4.7 and Podman Compose 1.0.3 (which was installed via `sudo dnf install podman-compose` and is very old). However I have installed the development version which is 1.0.4 and the network problem is solved.

**Comment by Reizake** [comment]
I also just did the docker compose socket to podman and that fixed it

**Comment by zantisit** [comment]
according to the error message, find the error line 1127. 
we will see the error is "missing networks: {missing_nets_str}"),
and the missing_nets_str is the join of missing_nets.
And the missing_nets is equal given_nets minus allnets.
So we can focus on the minus result, which is not as nice as we thought. 
Only when the minus result is 0, the program will be running without errors.
Let us print out the referred param's value.
```
print("srv_nets", srv_nets)
print("srv_nets", srv.get("networks", None))
print("nets",nets)
print("given_nets", given_nets)
print("allnets", allnets)
```
you will get output as ,
```
using podman version: 4.2.0
srv_nets ["zantisit_ml_net={'ipv4_address': '172.19.0.1'}"]
srv_nets {'zantisit_ml_net':{'ipv4_address': '172.19.0.1'}}
nets {'zantisit_ml_net': {'ipam': {'driver': 'default', 'config': [{'subnet': '172.27.0.0/24'}]}}}
given_nets {'zantisit_ml_net'}
allnets {"zantisit_ml_net={'ipv4_address': '172.27.0.1'}"}
Tracebak (most recent call last):
...
```
as the given_nets is not equal to allnets. so given_nets minus allnets is not 0.
So we just need to change get allnets
from
`allnets.update(srv_nets)`
to
`allnets.update(srv.get("networks", None) or default_net)`
this error will be fixed.
-------------------
as the progress goes on, two more bugs are waiting, 
on line 557 and 588
change
`cnt_nets = norm_as_list(cnt.get("networks", None) or default_net`
to 
`cnt_nets = (cnt.get("networks", None) or deafult_net)`
---------------------
And we can see there's TODO tobe done. if any one is interesting, you can try to improve it. 
Some of the TODO looks simple. For example the TODO between line 557 and 588.

**Comment by mokibit** [comment]
I can no longer reproduce this issue with the following configuration:
Environment:
```
Debian GNU/Linux 13 (trixie)
podman-compose version 1.6.0
podman version 5.4.2
```

`docker-compose.yml` file:
```
networks:
  podman:
    external:
      name: podman

services:
  app:
    image: 'busybox'
    restart: always
    command: ["sleep", "3600"]
    networks:
      podman:
        ipv4_address: 10.88.2.2
```
Container was successfully started:
```
$ podman-compose up -d
<...>
test-podman-compose_app_1
$ podman ps -a
CONTAINER ID  IMAGE                                                              COMMAND               CREATED        STATUS        PORTS                      NAMES
9a0ac7385f1f  docker.io/library/busybox:latest                                   sleep 3600            2 seconds ago  Up 3 seconds                             test-podman-compose_app_1
```
The output confirms the container is on the `podman` network with the requested static IP address (10.88.2.2):
```
$ podman inspect test-podman-compose_app_1 --format '{{json .NetworkSettings.Networks}}' | python3 -m json.tool
{
    "podman": {
        "EndpointID": "",
        "Gateway": "10.88.0.1",
        "IPAddress": "10.88.2.2",
        ...
    }
}
```
The container starts successfully and is attached to the `podman` network with the requested static IP.
I am closing this issue as the current version of `podman-compose` correctly handles external networks with custom names. The bug was likely fixed in a subsequent release.
