### ISSUE TITLE
Please support build-time secrets

### ISSUE THREAD

**Issue by nodakai** [containers/podman-compose#589]
* https://docs.docker.com/compose/compose-file/build/#secrets
* https://docs.podman.io/en/latest/markdown/podman-build.1.html#secret-id-id-src-path

**Comment by muayyad-alsadi** [comment]
You are missing the top level secrets
Possibly external

https://github.com/compose-spec/compose-spec/blob/master/09-secrets.md

**Comment by joe733** [comment]
It works, here's my updated `compose.yaml`

```yaml
secrets:
  nextcloud-admin-password:
    environment: ${nextcloud_admin_password}
    external: true
  nextcloud-admin-user:
    environment: ${nextcloud_admin_user}
    external: true
  postgres-db:
    environment: ${postgres_db}
    external: true
  postgres-password:
    environment: ${postgres_password}
    external: true
  postgres-user:
    environment: ${postgres_user}
    external: true

volumes:
  pgdb:
  nextcloud:


services:
  db:
    container_name: nc_home_db
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_DB: /run/secrets/postgres_db
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres-db
      - postgres-password
      - postgres-user
    volumes:
      - pgdb:/var/lib/postgresql/data

  app:
    container_name: nc_home_app
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: /run/secrets/postgres_db
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      NEXTCLOUD_ADMIN_PASSWORD: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_ADMIN_USER: /run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud-admin-password
      - nextcloud-admin-user
      - postgres-db
      - postgres-password
      - postgres-user
    volumes:
      - nextcloud:/var/www/html
```

I had to create each secret manually, as `podman-compose` won't create it from the environment variables, then I had to set `external: true` . But now I've some other problems: https://github.com/containers/podman-compose/issues/673#issuecomment-1529725877
