### ISSUE TITLE
stdout not showing up, only stderr

### ISSUE THREAD

**Issue by jedahan** [containers/podman-compose#605]
latest dev branch

```shell
# podman-compose --version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.4
podman --version 
podman version 4.3.1
exit code: 0
```

minimal example

```python
# counter.py
import sys
import time

counter = 0

while True:
    print(f"stdout {counter}")
    print(f"stderr {counter}", file=sys.stderr)
    counter = counter + 1
    time.sleep(10)
```

```bash
# this only shows stderr log lines, not stdout
podman-compose run counter python /counter.py
```

```yaml
# compose.yaml
name: counter

services:
  counter:
    image: docker.io/library/python:3.11-slim
    restart: unless-stopped
    volumes:
      - ./counter.py:/counter.py
    command: [ "python", "/counter.py" ]
```
