### ISSUE TITLE
"podman-compose up" fails with "--ip can only be set for a single network" when a service has more than one network

### ISSUE THREAD

**Issue by jaikiran** [containers/podman-compose#678]
Consider this trivial `docker-compose.yml` file:

```yaml
version: "2.4"

services:
  helloworld:
    image: hello-world:latest
    container_name: hello
    hostname: hello
    stdin_open: true
    tty: true
    networks:
      one:
        ipv4_address: 193.168.0.2
        ipv6_address: fe00:aaaa:aaaa:0::2
      two:
        ipv4_address: 193.168.100.2
        ipv6_address: fe00:aaaa:aaaa:100::2

networks:
  one:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.168.0.0/24
        - subnet: fe00:aaaa:aaaa:0::/64
  two:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.168.100.0/24
        - subnet: fe00:aaaa:aaaa:100::/64

```

The service `helloworld` is configured with 2 networks (both of which are defined later in that compose file). When using `docker-compose` to do `docker-compose up` this correctly creates the networks, the containers and starts the containers:

```console
docker-compose up       
[+] Running 3/3
 ⠿ Network multi-network_one  Created                                                                                                                                 0.0s
 ⠿ Network multi-network_two  Created                                                                                                                                 0.0s
 ⠿ Container hello            Created                                                                                                                                 0.0s
Attaching to hello
hello  | 
hello  | Hello from Docker!
hello  | ....
hello exited with code 0
```
`docker inspect` against that container even shows that the networks were properly connected to that container:
```console
"Networks": {
    "multi-network_one": {
        "IPAMConfig": {
            "IPv4Address": "193.168.0.2",
            "IPv6Address": "fe00:aaaa:aaaa:0::2"
        },
        "Links": null,
        "Aliases": [
            "hello",
            "helloworld",
            "622fddd38cd6"
        ],
        "NetworkID": "837629abb8ecd413866062782e2f9997e73a439754ebedd74289bc11f778951c",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "",
        "DriverOpts": null
    },
    "multi-network_two": {
        "IPAMConfig": {
            "IPv4Address": "193.168.100.2",
            "IPv6Address": "fe00:aaaa:aaaa:100::2"
        },
        "Links": null,
        "Aliases": [
            "hello",
            "helloworld",
            "622fddd38cd6"
        ],
        "NetworkID": "88cbb5dbfe3b3da2805b87d1e00bdee0a0f0f5a4425139f6b7e35c28249de5d5",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "",
        "DriverOpts": null
    }
}
```

Now, instead of `docker-compose` if I use `podman-compose` to do `podman-compose up` against the same file, I get this error:

```console
podman-compose up
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.4.0
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=test', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'test_one']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=test', '--label', 'com.docker.compose.project=test', '--driver', 'bridge', '--subnet', '193.168.0.0/24', '--subnet', 'fe00:aaaa:aaaa:0::/64', 'test_one']
['podman', 'network', 'exists', 'test_one']
['podman', 'network', 'exists', 'test_two']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=test', '--label', 'com.docker.compose.project=test', '--driver', 'bridge', '--subnet', '193.168.100.0/24', '--subnet', 'fe00:aaaa:aaaa:100::/64', 'test_two']
['podman', 'network', 'exists', 'test_two']
podman create --name=hello --label io.podman.compose.config-hash=a93a0a05d39a52c90d5000e96a2c6877f59dc459e25cb8c1e3e202c7d2b5f885 --label io.podman.compose.project=test --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@test.service --label com.docker.compose.project=test --label com.docker.compose.project.working_dir=/home/me/test --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=helloworld --net test_two,test_one --network-alias helloworld --ip=193.168.0.2 --ip6=fe00:aaaa:aaaa:0::2 --hostname hello -i --tty hello-world:latest
Error: --ip can only be set for a single network: invalid argument
exit code: 125
```
It appears that when `podman-compose` sees multiple networks for a service it uses the `--ip` (and `--ip6`) multiple times when creating a container and that's disallowed. 

In the case of `docker-compose`, where it succeeds, looking at the internal implementation of that command, it looks like `docker-compose` when it finds multiple networks for a service, it creates the container by attaching it to one single network (out of those N networks) and then after the container is created (and before it is started), it explicitly connects the container with the remaining N - 1 networks that are defined for that service. From what I can gather, it does that by explicitly calling the `/networks/{0}/connect` endpoint against the daemon process, after the container is created.

`podman-compose` version in use is:

```
podman-compose version: 1.0.6
```
