### ISSUE TITLE
the current implementation does not fully support multiple env_file 

### ISSUE THREAD

**Issue by NerdToMars** [containers/podman-compose#789]
following implementation seems not support config like:
```
version: '3'

services:
  hello:
    image: alpine
    entrypoint: ["sh"]
    command: ["-c", "env"]
    env_file:
      - a.env
      - b.env
```

https://github.com/containers/podman-compose/blob/bce40c2db30fb0ffb9264b5f51535c26f48fe983/podman_compose.py#L1566-L1571

might need to change to 
```
# Assuming args.env_file is a list of env_file paths
dotenv_dict = {}
if args.env_file:
    for env_file in args.env_file:
        dotenv_path = os.path.realpath(env_file)
        dotenv_dict.update(dotenv_to_dict(dotenv_path))

```

fyi: implementation of docker compose https://github.com/docker/compose/blob/9b4d577c65a87f49db4bdadd9e69f5f7a0ed4006/cmd/compose/compose.go#L536
