### ISSUE TITLE
Unable to set network MTU

### ISSUE THREAD

**Issue by tredeske** [containers/podman-compose#790]
**Describe the bug**

When driver_opts is used to set the MTU of a network, the setting has no effect.

```
networks:
  inner:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
      driver_opts:
        mtu: 9000
```

podman-compose -v
```
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.4.1
podman-compose version 1.0.6
podman --version 
podman version 4.4.1
```

**Environment:**
 - OS: RHEL 8

**Comment by tricepsbrachii** [comment]
Using `com.docker.network.driver.mtu` works for me. For example:

```
networks:
  default:
    name: test_network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1392
```
