### ISSUE TITLE
permission denied on Mounting

### ISSUE THREAD

**Issue by ThaSami** [containers/podman-compose#80]
I am trying to mount a file however it always gives "permission denied" 
and privileged : true 
seems not supported !
```

`version: '3.3'
services:

  DB:
    image: mysql:latest
    container_name: sql_server
#    privileged: true	  
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --init-file /data/application/initialize.sql
    volumes:
      - ./initialize.sql:/data/application/initialize.sql`
```

**Comment by lcarva** [comment]
Looks like this was resolved in https://github.com/containers/podman-compose/commit/27d3cafb7b33fd50c133004e7ebb5ba9f201bf90 ?

**Comment by ChengYen-Tang** [comment]
Hi, 
If I use  `privileged: true` in the docker-compose.yml.
I get this error. `yaml.scanner.ScannerError: mapping values are not allowed here`

podman-composer version  0.1.7dev

**Comment by muayyad-alsadi** [comment]
Are you sure your yaml is valid, try online yaml to json

**Comment by ChengYen-Tang** [comment]
Is that right? 

```
version: '3'
services:
  registry:
    image: registry:latest
    privileged: true
    volumes:
      - ./:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    environment:
        REGISTRY_STORAGE_DELETE_ENABLED: "true"
    restart: always
    container_name: registry

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 5000:80
    environment:
      - REGISTRY_TITLE=IoNetworks Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
    depends_on:
      - registry
    restart: always
    container_name: registry-ui
```

**Comment by mokibit** [comment]
Closing this issue as both reported problems have been resolved in the current version of podman-compose.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
Minimal `compose.yml`:
```
services:
  test:
    image: busybox:latest
    container_name: issue80_test
    privileged: true
    volumes:
      - ./test_file.txt:/data/test_file.txt:ro
    command: ["cat", "/data/test_file.txt"]
```
Commands to verify:
Start the container
```
$ podman-compose up -d
[...]
issue80_test
```
Check logs — file is readable (no permission denied)
```
$ podman-compose logs
[issue80_test]| Hello from mounted file!
```
Verify privileged mode is actually applied
```
$ podman inspect issue80_test --format='{{.HostConfig.Privileged}}'
true
```
Both `privileged: true` and file bind mounts now work correctly. The `--privileged` flag is properly passed to `podman`, and file mounts do not trigger permission denied errors. This was likely fixed in a release after the original report.

If anyone still encounters this on a recent podman/podman-compose version, please open a new issue with your environment details.
