### ISSUE TITLE
all containers get the same port mappings

### ISSUE THREAD

**Issue by Harnish** [containers/podman-compose#83]
When running podman-compose with a config with more than 1 container, all containers get the same port forwarding.

```
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: defaultpw
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8229:8080"
```
To start my config I run:
```
 podman-compose -p mdb -f podman-compose-mariadb.yaml up
```
when I run podman ps it shows both containers have both port forwards going to them.  
```
➜  ~ podman ps
CONTAINER ID  IMAGE                             COMMAND               CREATED        STATUS            PORTS                                           NAMES
b8a362e02472  docker.io/library/adminer:latest  php -S [::]:8080 ...  6 seconds ago  Up 3 seconds ago  0.0.0.0:8229->8080/tcp, 0.0.0.0:3306->3306/tcp  mdb_adminer_1
576f606d2410  docker.io/library/mariadb:latest  mysqld                7 seconds ago  Up 3 seconds ago  0.0.0.0:8229->8080/tcp, 0.0.0.0:3306->3306/tcp  mdb_db_1
```

I just pulled the latest version and it has the same problem:
```
➜  ~ md5sum /usr/local/bin/podman-compose
2547131631078811b7438e7d369d7c5f  /usr/local/bin/podman-compose
```
