### ISSUE TITLE
How can I configure the bridge network to be accessible from other machines?

### ISSUE THREAD

**Issue by Sheng2216** [containers/podman-compose#865]
Hello everyone, I am new to podman-compose. I need to host a service called Zigbee2MQTT on my Debian host machine. However, I am having trouble accessing the web UI of the service from another machine on the same local area network(I can access from the host machine only). How can I address this issue? I have learned that by using sudo (which I need to access the Zigbee dongle attached to my host machine), a bridge network is created. However, this bridge network is isolated, and no one except the host machine can access it. 

I also tried adding network_mode=host to the .yml file, but I received an error message stating that I cannot use multiple networks. `Error: cannot set multiple networks without bridge network mode, selected mode host: invalid argument`
I apologize if this seems like a dumb question. Any help would be greatly appreciated!

Here is my docker-compose.yml file:
```
services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    #network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:1.32.2
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Asian/Hong_Kong
    devices:
      - /dev/ttyUSB6:/dev/ttyUSB6
    #network_mode: host
```

**Comment by Sheng2216** [comment]
I noticed that when running Podman in a clean environment without Docker installed, it functions as expected. However, if Docker is pre-installed, it causes conflicts and only Docker works properly.

**Comment by mokibit** [comment]
After investigating, I am closing this issue because this is not a bug in `podman-compose` - the behavior you are seeing is expected, and your original goal (accessing the web UI from other machines on the LAN) is already achievable with the bridge network and port mappings you already have.

1. Why `network_mode: host` fails with `podman-compose`

`podman-compose` creates a pod by default to group your containers together. When a pod is created, it gets its own network namespace (a bridge network). Every container you add to that pod shares the pod's network namespace.

When you set `network_mode: host` on a service, you are telling Podman to put that container in the host's network namespace instead. But because the container is also part of a pod that has a bridge network, Podman sees a conflict:
```
Error: cannot set multiple networks without bridge network mode, selected mode host: invalid argument
```
This error comes from Podman itself, not `podman-compose`, and it is correct: a single container cannot simultaneously join a pod's bridge network and use the host network.

2. If you really need `network_mode: host`
You must disable the pod. Choose one of the following:
A) Command line:
```
sudo podman-compose --in-pod=false up -d
```
B) In your `docker-compose.yml`:
```
x-podman:
  in_pod: false
services:
  zigbee2mqtt:
    network_mode: host
    # REMOVE the ports: section — it is ignored in host mode
```
3. You probably do not need `network_mode: host`
Your original `docker-compose.yml` already has the correct setup for LAN access:
```
services:
  zigbee2mqtt:
    ports:
      - "8080:8080"
```
This tells Podman to map port 8080 on the host to port 8080 in the container. By default, the mapping binds to 0.0.0.0 (all interfaces), so any machine on the same LAN can reach http://<your-debian-ip>:8080. The container's internal bridge network does not prevent this; the port mapping publishes the port on your host's network interfaces.

If you still cannot access the service after verifying your firewall rules and the application's binding address, feel free to reopen the issue and provide a minimal reproducible `compose.yml`, the exact commands you ran, and their full output.
