### ISSUE TITLE
Fails to handle the `service_healthy` condition of a `depends_on` element

### ISSUE THREAD

**Issue by candleindark** [containers/podman-compose#866]
**Describe the bug**
`podman-compose` fails to handle the `service_healthy` condition of a [`depends_on`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1) element.

**To Reproduce**

1. Create the following `docker-compose.yml` file

```yaml
services:
  base:
    image: docker.io/debian
    command: [ "tail", "-f", "/dev/null" ]
    healthcheck:
      test: [ "CMD", "false" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m

  dependent:
    image: docker.io/debian
    depends_on:
      base:
        condition: service_healthy
    command: [ "tail", "-f", "/dev/null" ]
```

2. Run `podman-compose -f docker-compose.yml up -d` in the containing directory

**Expected behavior**
The container corresponding to the `dependent` service never starts since the `base` can never be healthy.

**Actual behavior**
The container corresponding to the `dependent` service always starts.

**Output**

```
podman-compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.6
podman --version 
podman version 4.3.1
exit code: 0
```

**Environment:**
 - OS: Debian GNU/Linux 12 (bookworm)
 - podman version: 4.3.1
 - podman compose version: 1.0.6
