### ISSUE TITLE
RFE: Support network aliases

### ISSUE THREAD

**Issue by larsks** [containers/podman-compose#88]
A `docker-compose.yml` file may define one or more aliases for a container, such that other containers in the same compose can use those aliases rather than the container name to resolve its ip address. E.g. from [the documentation](https://docs.docker.com/compose/compose-file/#aliases):

```
services:
  some-service:
    networks:
      some-network:
        aliases:
         - alias1
         - alias3
      other-network:
        aliases:
         - alias2
```

Support this in `podman-compose` would permit a wider range of `docker-compose` setups to be used without modification.

This would require containers/libpod#4530 to be implemented first.

**Comment by Schlumpf9** [comment]
Does this problem still exist? I am not able to start a container using aliases with podman-compose at the moment...
I always receive a KeyError on startup:
```
  File ".../python3.9/site-packages/podman_compose.py", line 558, in assert_cnt_nets
    net_desc = nets[net] or {}
KeyError: "system={'aliases': ['db']}"
```

Using the following compose.yaml:
```
version: "3.9"
services:
  mariadb:
    image: mariadb:10.6
    networks:
      system:
        aliases:
          - db
      web:
        asliases:
          - db
```

**Comment by muayyad-alsadi** [comment]
quote from podman manpage

```
   --network-alias=alias
       Add network-scoped alias for the container.  NOTE: A container will only have access to aliases on the first network that it joins. This is a limitation that will be removed in a later release.
```

so regarding

```yaml
version: "3.9"
services:
  mariadb:
    image: mariadb:10.6
    networks:
      system:
        aliases:
          - sysdb
      web:
        aliases:
          - webdb
networks:
  default:
    name: "system"
  web:
```


@rhatdan do you suggest a specific sequence of podman commands
to acchive that

```
$ podman network myproj-system
$ podman network myproj-web
$ podman run -ti --rm --network myproj-system --network-alias sysdb --network myproj-web --network-alias webdb  busybox /bin/sh
```
