### ISSUE TITLE
env_file ignored for environment

### ISSUE THREAD

**Issue by Vic-M** [containers/podman-compose#891]
**Describe the bug**
Although podman-compose passes the values in the env_file to the container, it ignores the value in the compose file

**To Reproduce**
.env
```
SOME_ENV_VALUE=qqq
```

docker-compose.yml
```
version: "3.8"

services:
  container:
    image: some_image
    env_file:
      - ./../.env
     environment:
      SOME_ENV: ${SOME_ENV_VALUE}
```

**Expected behavior**
```
root@7ad1edad1404:/var/www/html# echo $SOME_ENV
qqq
root@7ad1edad1404:/var/www/html# echo $SOME_ENV_VALUE
qqq
```

**Actual behavior**
```
root@7ad1edad1404:/var/www/html# echo $SOME_ENV

root@7ad1edad1404:/var/www/html# echo $SOME_ENV_VALUE
qqq
```

**Output**

```
podman-compose version
podman-compose version 1.0.7
podman version 4.9.3-dev
```

**Comment by mokibit** [comment]
As `podman-compose` closely emulates `docker-compose`, this is what documentation of `docker-compose` says regarding `.env ` file, `env_file:`, `environment` and variable interpolation:
 `docker-compose` only sets and interpolates environment variables from `.env` file used in `compose.yml` file by section `env_file:` if `.env` file is located in the same directory as `compose.yml` file itself.
Documented here: 
https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#substitute-with---env-file
"The `.env` file should be placed at the root of the project directory next to your `compose.yaml` file. <...> If you define a variable in your `.env` file, you can reference it directly in your `compose.yaml` with the environment attribute."
I tested it with `compose.yml` file:
```
services:
  container:
    image: debian:bookworm
    env_file:
      - .env
    environment:
      SOME_ENV: ${SOME_ENV_VALUE}
    command: tail -F anything
```
`.env` file:
```
SOME_ENV_VALUE=qqq
```
and this directory structure:
```
path/to/docker-compose.yml
path/to/.env
```
Command `docker-compose up -d` was run, then `docker exec -it <container-name> bin/bash`. Output of `env` command inside container was as expected:
```
<...>
SOME_ENV=qqq
SOME_ENV_VALUE=qqq
```
If one wants to pass environment variable from `.env` file and use it directly in `compose.yml` file via interpolation, `.env`file must be located relative to the location of `compose.yml` file.
