### ISSUE TITLE
FR: Enabling GPU access to service containers 

### ISSUE THREAD

**Issue by mokeyish** [containers/podman-compose#919]
Currently, the following configuration is not work on podman-compose.

```yaml
services:
  test:
    image: nvidia/cuda:12.3.1-base-ubuntu20.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

https://docs.docker.com/compose/gpu-support/
