### ISSUE TITLE
RFE: support "nocopy:false"

### ISSUE THREAD

**Issue by ensc** [containers/podman-compose#96]
I want to make the content of one container's subdirectory available in another one.  I tried:

```yaml
version: "3.7"

services:
  nginx:
    ...
    volumes:
      - type: volume
        source: assets
        target: /opt/assets
        read_only: true

    depends_on:
      - sstate

  sstate:
    ...
    volumes:
      - type: volume
        source: assets
        target: /opt/assets
        volume:
          nocopy: false

volumes:
  assets:
```

I expect that the `assets` volume is filled with the content of `/opt/assets` when the `sstate` container is started.  But volume does not contain any data and `opt/assets` is empty both in the `sstate` and the `nginx` container.

**Comment by mokibit** [comment]
Closing this issue because the reported scenario works correctly with current versions:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
I verified using the compose file from the report. The `assets` volume is populated with the image contents from `/opt/assets` when the `sstate` container starts, and the `nginx` container can read the data from the same volume mounted read-only.
`docker-compose.yml`:
```
services:
  nginx:
    image: busybox
    command: ["sleep", "3600"]
    volumes:
      - type: volume
        source: assets
        target: /opt/assets
        read_only: true
    depends_on:
      - sstate
  sstate:
    build:
      context: .
      dockerfile: Dockerfile.sstate
    command: ["sleep", "3600"]
    volumes:
      - type: volume
        source: assets
        target: /opt/assets
        volume:
          nocopy: false
volumes:
  assets:
```
`Dockerfile.sstate`:
```
FROM busybox
RUN mkdir -p /opt/assets && echo "hello from image" > /opt/assets/data.txt
```
Run these commands for confirmation:
```
$ podman-compose up -d --build

# Check that the volume contains the image data
$ podman exec nocopy_reproduction_sstate_1 cat /opt/assets/data.txt
hello from image  #  this is the expected output

# Check that nginx can read it too
podman exec nocopy_reproduction_nginx_1 cat /opt/assets/data.txt
hello from image  #  this is the expected output
```
While the behavioral symptom described here is resolved, there is a related issue: the `nocopy` option is parsed from the compose file but never forwarded to `podman`. 
This means `nocopy: true` is still effectively ignored. That specific problem is being tracked in (https://github.com/containers/podman-compose/issues/1459).
