### ISSUE TITLE
Repeated wait time options when using `podman-compose stop`

### ISSUE THREAD

**Issue by apeteri** [containers/podman-compose#962]
**Description:**

As `podman-compose` moves through service entries, each issued `podman stop` command receives an additional `-t 10` option:

```console
$ podman-compose up -d
...

$ podman-compose stop
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.9.4-rhel
podman stop -t 10 test_service2_1
test_service2_1
exit code: 0
podman stop -t 10 -t 10 test_service1_1
             ^^^^^^^^^^
test_service1_1
exit code: 0
```

**Environment:**

 - OS: RHEL 9
 - podman version: 4.9.4-rhel
 - podman compose version: 1.0.6 (installed via pip)

**Contents of docker-compose.yml:**

```yaml
services:
  service1:
    image: docker.io/library/ubuntu:latest
  service2:
    image: docker.io/library/ubuntu:latest
```
